// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/protobuf/api.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Protocol Buffers - Google's data interchange format
// Copyright 2008 Google Inc.  All rights reserved.
// https://developers.google.com/protocol-buffers/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// 'import SwiftProtobuf' suppressed, this proto file is meant to be bundled in the runtime.

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: ProtobufAPIVersionCheck {
  struct _2: ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Api is a light-weight descriptor for an API Interface.
///
/// Interfaces are also described as "protocol buffer services" in some contexts,
/// such as by the "service" keyword in a .proto file, but they are different
/// from API Services, which represent a concrete implementation of an interface
/// as opposed to simply a description of methods and bindings. They are also
/// sometimes simply referred to as "APIs" in other contexts, such as the name of
/// this message itself. See https://cloud.google.com/apis/design/glossary for
/// detailed terminology.
///
/// New usages of this message as an alternative to ServiceDescriptorProto are
/// strongly discouraged. This message does not reliability preserve all
/// information necessary to model the schema and preserve semantics. Instead
/// make use of FileDescriptorSet which preserves the necessary information.
public struct Google_Protobuf_Api: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The fully qualified name of this interface, including package name
  /// followed by the interface's simple name.
  public var name: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(48, 24), hasBit: (0, 2)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(48, 24), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 2)) }
  }

  /// The methods of this interface, in unspecified order.
  public var methods: [Google_Protobuf_Method] {
    get { _storage.value(at: 8, hasBit: (0, 4)) }
    set { _uniqueStorage().updateValue(at: 8, to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 4)) }
  }

  /// Any metadata attached to the interface.
  public var options: [Google_Protobuf_Option] {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(16, 12), hasBit: (0, 8)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(16, 12), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 8)) }
  }

  /// A version string for this interface. If specified, must have the form
  /// `major-version.minor-version`, as in `1.10`. If the minor version is
  /// omitted, it defaults to zero. If the entire version field is empty, the
  /// major version is derived from the package name, as outlined below. If the
  /// field is not empty, the version in the package name will be verified to be
  /// consistent with what is provided here.
  ///
  /// The versioning schema uses [semantic
  /// versioning](http://semver.org) where the major version number
  /// indicates a breaking change and the minor version an additive,
  /// non-breaking change. Both version numbers are signals to users
  /// what to expect from different versions, and should be carefully
  /// chosen based on the product plan.
  ///
  /// The major version is also reflected in the package name of the
  /// interface, which must end in `v<major-version>`, as in
  /// `google.feature.v1`. For major versions 0 and 1, the suffix can
  /// be omitted. Zero major versions must only be used for
  /// experimental, non-GA interfaces.
  public var version: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(64, 36), hasBit: (0, 16)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(64, 36), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 16)) }
  }

  /// Source context for the protocol buffer service represented by this
  /// message.
  public var sourceContext: Google_Protobuf_SourceContext {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(24, 16), default: Google_Protobuf_SourceContext(), hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(24, 16), to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `sourceContext` has been explicitly set.
  public var hasSourceContext: Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `sourceContext`. Subsequent reads from it will return its default value.
  public mutating func clearSourceContext() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(24, 16), type: Google_Protobuf_SourceContext.self, hasBit: (0, 1)) }

  /// Included interfaces. See [Mixin][].
  public var mixins: [Google_Protobuf_Mixin] {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(32, 20), hasBit: (0, 32)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(32, 20), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 32)) }
  }

  /// The source syntax of the service.
  public var syntax: Google_Protobuf_Syntax {
    get { _storage.value(at: 4, default: .proto2, hasBit: (0, 64)) }
    set { _uniqueStorage().updateValue(at: 4, to: newValue, willBeSet: newValue != .proto2, hasBit: (0, 64)) }
  }

  /// The source edition string, only valid when syntax is SYNTAX_EDITIONS.
  public var edition: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(80, 48), hasBit: (0, 128)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(80, 48), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 128)) }
  }

  public var unknownFields: UnknownStorage {
    get { _storage.unknownFields }
    _modify {
      _ = _uniqueStorage()
      yield &_storage.unknownFields
    }
  }

  public init() {}

  private var _storage = SwiftProtobuf._MessageStorage(schema: Self.messageSchema)
  private mutating func _uniqueStorage() -> SwiftProtobuf._MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  public mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf._MessageStorageToken) { _ = _uniqueStorage() }
  public func _protobuf_extensionStorageImpl() -> AnyObject { _storage.extensionStorage }
  public mutating func _protobuf_uniqueExtensionStorageImpl() -> AnyObject { _uniqueStorage().extensionStorage }
}

/// Method represents a method of an API interface.
///
/// New usages of this message as an alternative to MethodDescriptorProto are
/// strongly discouraged. This message does not reliability preserve all
/// information necessary to model the schema and preserve semantics. Instead
/// make use of FileDescriptorSet which preserves the necessary information.
public struct Google_Protobuf_Method: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The simple name of this method.
  public var name: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(16, 12), hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(16, 12), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 1)) }
  }

  /// A URL of the input message type.
  public var requestTypeURL: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(32, 24), hasBit: (0, 2)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(32, 24), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 2)) }
  }

  /// If true, the request is streamed.
  public var requestStreaming: Bool {
    get { _storage.value(at: 1, hasBit: (0, 4)) }
    set { _uniqueStorage().updateValue(at: 1, to: newValue, willBeSet: newValue != false, hasBit: (0, 4)) }
  }

  /// The URL of the output message type.
  public var responseTypeURL: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(48, 36), hasBit: (0, 8)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(48, 36), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 8)) }
  }

  /// If true, the response is streamed.
  public var responseStreaming: Bool {
    get { _storage.value(at: 2, hasBit: (0, 16)) }
    set { _uniqueStorage().updateValue(at: 2, to: newValue, willBeSet: newValue != false, hasBit: (0, 16)) }
  }

  /// Any metadata attached to the method.
  public var options: [Google_Protobuf_Option] {
    get { _storage.value(at: 8, hasBit: (0, 32)) }
    set { _uniqueStorage().updateValue(at: 8, to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 32)) }
  }

  /// The source syntax of this method.
  ///
  /// This field should be ignored, instead the syntax should be inherited from
  /// Api. This is similar to Field and EnumValue.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  public var syntax: Google_Protobuf_Syntax {
    get { _storage.value(at: 4, default: .proto2, hasBit: (0, 64)) }
    set { _uniqueStorage().updateValue(at: 4, to: newValue, willBeSet: newValue != .proto2, hasBit: (0, 64)) }
  }

  /// The source edition string, only valid when syntax is SYNTAX_EDITIONS.
  ///
  /// This field should be ignored, instead the edition should be inherited from
  /// Api. This is similar to Field and EnumValue.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  public var edition: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(64, 48), hasBit: (0, 128)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(64, 48), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 128)) }
  }

  public var unknownFields: UnknownStorage {
    get { _storage.unknownFields }
    _modify {
      _ = _uniqueStorage()
      yield &_storage.unknownFields
    }
  }

  public init() {}

  private var _storage = SwiftProtobuf._MessageStorage(schema: Self.messageSchema)
  private mutating func _uniqueStorage() -> SwiftProtobuf._MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  public mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf._MessageStorageToken) { _ = _uniqueStorage() }
  public func _protobuf_extensionStorageImpl() -> AnyObject { _storage.extensionStorage }
  public mutating func _protobuf_uniqueExtensionStorageImpl() -> AnyObject { _uniqueStorage().extensionStorage }
}

/// Declares an API Interface to be included in this interface. The including
/// interface must redeclare all the methods from the included interface, but
/// documentation and options are inherited as follows:
///
/// - If after comment and whitespace stripping, the documentation
///   string of the redeclared method is empty, it will be inherited
///   from the original method.
///
/// - Each annotation belonging to the service config (http,
///   visibility) which is not set in the redeclared method will be
///   inherited.
///
/// - If an http annotation is inherited, the path pattern will be
///   modified as follows. Any version prefix will be replaced by the
///   version of the including interface plus the [root][] path if
///   specified.
///
/// Example of a simple mixin:
///
///     package google.acl.v1;
///     service AccessControl {
///       // Get the underlying ACL object.
///       rpc GetAcl(GetAclRequest) returns (Acl) {
///         option (google.api.http).get = "/v1/{resource=**}:getAcl";
///       }
///     }
///
///     package google.storage.v2;
///     service Storage {
///       rpc GetAcl(GetAclRequest) returns (Acl);
///
///       // Get a data record.
///       rpc GetData(GetDataRequest) returns (Data) {
///         option (google.api.http).get = "/v2/{resource=**}";
///       }
///     }
///
/// Example of a mixin configuration:
///
///     apis:
///     - name: google.storage.v2.Storage
///       mixins:
///       - name: google.acl.v1.AccessControl
///
/// The mixin construct implies that all methods in `AccessControl` are
/// also declared with same name and request/response types in
/// `Storage`. A documentation generator or annotation processor will
/// see the effective `Storage.GetAcl` method after inheriting
/// documentation and annotations as follows:
///
///     service Storage {
///       // Get the underlying ACL object.
///       rpc GetAcl(GetAclRequest) returns (Acl) {
///         option (google.api.http).get = "/v2/{resource=**}:getAcl";
///       }
///       ...
///     }
///
/// Note how the version in the path pattern changed from `v1` to `v2`.
///
/// If the `root` field in the mixin is specified, it should be a
/// relative path under which inherited HTTP paths are placed. Example:
///
///     apis:
///     - name: google.storage.v2.Storage
///       mixins:
///       - name: google.acl.v1.AccessControl
///         root: acls
///
/// This implies the following inherited HTTP annotation:
///
///     service Storage {
///       // Get the underlying ACL object.
///       rpc GetAcl(GetAclRequest) returns (Acl) {
///         option (google.api.http).get = "/v2/acls/{resource=**}:getAcl";
///       }
///       ...
///     }
public struct Google_Protobuf_Mixin: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The fully qualified name of the interface which is included.
  public var name: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(16, 12), hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(16, 12), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 1)) }
  }

  /// If non-empty specifies a path under which inherited HTTP paths
  /// are rooted.
  public var root: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(32, 24), hasBit: (0, 2)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(32, 24), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 2)) }
  }

  public var unknownFields: UnknownStorage {
    get { _storage.unknownFields }
    _modify {
      _ = _uniqueStorage()
      yield &_storage.unknownFields
    }
  }

  public init() {}

  private var _storage = SwiftProtobuf._MessageStorage(schema: Self.messageSchema)
  private mutating func _uniqueStorage() -> SwiftProtobuf._MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  public mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf._MessageStorageToken) { _ = _uniqueStorage() }
  public func _protobuf_extensionStorageImpl() -> AnyObject { _storage.extensionStorage }
  public mutating func _protobuf_uniqueExtensionStorageImpl() -> AnyObject { _uniqueStorage().extensionStorage }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.protobuf"

extension Google_Protobuf_Api: Message, _MessageImplementationBase {
  public static let protoMessageName: String = _protobuf_package + ".Api"
  #if _pointerBitWidth(_64)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0`\0\0\u{8}\0\0\0\0\0\u{1}\0\0\u{9}\0\0\u{1}\0\0\0\00\0\0\u{1}\0\0\0\u{9}\u{2}\0\0\0\u{2}\u{8}\0\0\u{2}\0\u{2}\0\u{b}\u{3}\0\0\0\u{2}\u{10}\0\0\u{3}\0\u{3}\0\u{b}\u{4}\0\0\0\0@\0\0\u{4}\0\0\0\u{9}\u{5}\0\0\0\0\u{18}\0\0\0\0\u{4}\0\u{b}\u{6}\0\0\0\u{2} \0\0\u{5}\0\u{5}\0\u{b}\u{7}\0\0\0\0\u{4}\0\0\u{6}\0\u{1}\0\u{e}\u{8}\0\0\0\0P\0\0\u{7}\0\0\0\u{9}\u{13}\0google.protobuf.Api" }
  #elseif _pointerBitWidth(_32)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0<\0\0\u{8}\0\0\0\0\0\u{1}\0\0\u{9}\0\0\u{1}\0\0\0\0\u{18}\0\0\u{1}\0\0\0\u{9}\u{2}\0\0\0\u{2}\u{8}\0\0\u{2}\0\u{2}\0\u{b}\u{3}\0\0\0\u{2}\u{c}\0\0\u{3}\0\u{3}\0\u{b}\u{4}\0\0\0\0$\0\0\u{4}\0\0\0\u{9}\u{5}\0\0\0\0\u{10}\0\0\0\0\u{4}\0\u{b}\u{6}\0\0\0\u{2}\u{14}\0\0\u{5}\0\u{5}\0\u{b}\u{7}\0\0\0\0\u{4}\0\0\u{6}\0\u{1}\0\u{e}\u{8}\0\0\0\00\0\0\u{7}\0\0\0\u{9}\u{13}\0google.protobuf.Api" }
  #else
    #error("Unsupported platform")
  #endif
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_reflectionData: StaticString { "d\u{1}\0\00?$\\a[?s'LtW2\u{4}H|# '\u{11}-#t\u{1a}\u{5}z<\u{1f}W{Pj@cnVLfdI\u{3}?\u{1b}f_\u{e}`kz\u{2}VVE\u{6}%TD8k&\u{1f}j\u{1b}0$k\u{14}W,FX\u{8}G=Hjk\u{c}-\u{f}M;^{\u{14}4\u{f}\u{15}D\u{8}-\u{e}\u{8}K&K0-2`\u{f}I\u{19}\u{11}?h$<$O\u{7}<L{5\u{14}\0q6\u{13}\u{19}\u{1f}z/cLE^U&(\u{10}\u{1}\u{12}\u{1e}\u{5}8W\u{1d}\"Gg\u{19}\u{1}\0" }

  public static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, performNontrivialFieldOperation: _protobuf_performNontrivialFieldOperation, performOnSubmessageStorage: _protobuf_performOnSubmessageStorage, performOnRawEnumValues: _protobuf_performOnRawEnumValues, mapEntrySchema: _protobuf_mapEntrySchema, performOnMapEntry: _protobuf_performOnMapEntry)

  private static func _protobuf_performNontrivialFieldOperation(for token: SwiftProtobuf.MessageSchema.TrampolineToken, operation: SwiftProtobuf.NontrivialFieldOperation, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage) -> Bool {
    switch token.index {
    case 1: return storage.performNontrivialFieldOperation(operation, field: field, type: Google_Protobuf_Syntax.self)
    case 2: return storage.performNontrivialFieldOperation(operation, field: field, type: [Google_Protobuf_Method].self)
    case 3: return storage.performNontrivialFieldOperation(operation, field: field, type: [Google_Protobuf_Option].self)
    case 4: return storage.performNontrivialFieldOperation(operation, field: field, type: Google_Protobuf_SourceContext.self)
    case 5: return storage.performNontrivialFieldOperation(operation, field: field, type: [Google_Protobuf_Mixin].self)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnSubmessageStorage(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    case 2: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: [Google_Protobuf_Method].self, perform: perform)
    case 3: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: [Google_Protobuf_Option].self, perform: perform)
    case 4: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: Google_Protobuf_SourceContext.self, perform: perform)
    case 5: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: [Google_Protobuf_Mixin].self, perform: perform)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnRawEnumValues(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf.EnumSchema, inout Int32) throws -> Bool, onInvalidValue: (Int32) throws -> Void) throws {
    switch token.index {
    case 1: return try storage.performOnRawEnumValues(of: field, operation: operation, type: Google_Protobuf_Syntax.self, enumSchema: Google_Protobuf_Syntax.enumSchema, perform: perform, onInvalidValue: onInvalidValue)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_mapEntrySchema(for token: SwiftProtobuf.MessageSchema.TrampolineToken) -> SwiftProtobuf.MessageSchema {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnMapEntry(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, workingSpace: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, deterministicOrdering: Bool, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  public func _protobuf_messageStorage(accessToken: SwiftProtobuf._MessageStorageToken) -> AnyObject { _storage }

}

extension Google_Protobuf_Method: Message, _MessageImplementationBase {
  public static let protoMessageName: String = _protobuf_package + ".Method"
  #if _pointerBitWidth(_64)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0P\0\0\u{8}\0\0\0\0\0\0\0\0\u{9}\0\0\u{1}\0\0\0\0\u{10}\0\0\0\0\0\0\u{9}\u{2}\0\0\0\0 \0\0\u{1}\0\0\0\u{9}\u{3}\0\0\0\0\u{1}\0\0\u{2}\0\0\0\u{8}\u{4}\0\0\0\00\0\0\u{3}\0\0\0\u{9}\u{5}\0\0\0\0\u{2}\0\0\u{4}\0\0\0\u{8}\u{6}\0\0\0\u{2}\u{8}\0\0\u{5}\0\u{2}\0\u{b}\u{7}\0\0\0\0\u{4}\0\0\u{6}\0\u{1}\0\u{e}\u{8}\0\0\0\0@\0\0\u{7}\0\0\0\u{9}\u{16}\0google.protobuf.Method" }
  #elseif _pointerBitWidth(_32)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0<\0\0\u{8}\0\0\0\0\0\0\0\0\u{9}\0\0\u{1}\0\0\0\0\u{c}\0\0\0\0\0\0\u{9}\u{2}\0\0\0\0\u{18}\0\0\u{1}\0\0\0\u{9}\u{3}\0\0\0\0\u{1}\0\0\u{2}\0\0\0\u{8}\u{4}\0\0\0\0$\0\0\u{3}\0\0\0\u{9}\u{5}\0\0\0\0\u{2}\0\0\u{4}\0\0\0\u{8}\u{6}\0\0\0\u{2}\u{8}\0\0\u{5}\0\u{2}\0\u{b}\u{7}\0\0\0\0\u{4}\0\0\u{6}\0\u{1}\0\u{e}\u{8}\0\0\0\00\0\0\u{7}\0\0\0\u{9}\u{16}\0google.protobuf.Method" }
  #else
    #error("Unsupported platform")
  #endif
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_reflectionData: StaticString { "T\u{2}\0\0\u{10}\u{15}O\u{b}\u{6}R\u{1}%m7'\\/TpGh%z >79^\0Lc\u{18}eJnI1&9G\u{1a}=,\u{12}\tK'\u{5}v\u{7f}\u{13}ss\u{6}ZTq\u{1f}4<~z\u{6}@;5T8;\u{15}T\u{10}j\rS\042\r}\u{1}~-\u{1b}\u{15}\u{17}A=Yu\u{13}a\\CW\u{1b}\u{1}`A\u{16}1y\0i \u{7f}\u{12}K\u{11}\u{e}\u{17}\\\u{3}y*g\rJOv2NCD].\\(\u{17}v\u{4}p\u{f}YOAz2J]M\u{10}\u{6}\u{8}WI\0%|DF>D&x\u{1e}:\u{17}z3nT\u{10}aksAkngzAQ`U\u{b}$tcT\u{8}\0\0" }

  public static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, performNontrivialFieldOperation: _protobuf_performNontrivialFieldOperation, performOnSubmessageStorage: _protobuf_performOnSubmessageStorage, performOnRawEnumValues: _protobuf_performOnRawEnumValues, mapEntrySchema: _protobuf_mapEntrySchema, performOnMapEntry: _protobuf_performOnMapEntry)

  private static func _protobuf_performNontrivialFieldOperation(for token: SwiftProtobuf.MessageSchema.TrampolineToken, operation: SwiftProtobuf.NontrivialFieldOperation, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage) -> Bool {
    switch token.index {
    case 1: return storage.performNontrivialFieldOperation(operation, field: field, type: Google_Protobuf_Syntax.self)
    case 2: return storage.performNontrivialFieldOperation(operation, field: field, type: [Google_Protobuf_Option].self)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnSubmessageStorage(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    case 2: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: [Google_Protobuf_Option].self, perform: perform)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnRawEnumValues(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf.EnumSchema, inout Int32) throws -> Bool, onInvalidValue: (Int32) throws -> Void) throws {
    switch token.index {
    case 1: return try storage.performOnRawEnumValues(of: field, operation: operation, type: Google_Protobuf_Syntax.self, enumSchema: Google_Protobuf_Syntax.enumSchema, perform: perform, onInvalidValue: onInvalidValue)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_mapEntrySchema(for token: SwiftProtobuf.MessageSchema.TrampolineToken) -> SwiftProtobuf.MessageSchema {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnMapEntry(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, workingSpace: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, deterministicOrdering: Bool, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  public func _protobuf_messageStorage(accessToken: SwiftProtobuf._MessageStorageToken) -> AnyObject { _storage }

}

extension Google_Protobuf_Mixin: Message, _MessageImplementationBase {
  public static let protoMessageName: String = _protobuf_package + ".Mixin"
  #if _pointerBitWidth(_64)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\00\0\0\u{2}\0\0\0\0\0\0\0\0\u{3}\0\0\u{1}\0\0\0\0\u{10}\0\0\0\0\0\0\u{9}\u{2}\0\0\0\0 \0\0\u{1}\0\0\0\u{9}\u{15}\0google.protobuf.Mixin" }
  #elseif _pointerBitWidth(_32)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0$\0\0\u{2}\0\0\0\0\0\0\0\0\u{3}\0\0\u{1}\0\0\0\0\u{c}\0\0\0\0\0\0\u{9}\u{2}\0\0\0\0\u{18}\0\0\u{1}\0\0\0\u{9}\u{15}\0google.protobuf.Mixin" }
  #else
    #error("Unsupported platform")
  #endif
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_reflectionData: StaticString { "8\0\0\0@<_)1J\0)h\0]8GlL\u{f}Y\u{c}a\u{e}C\u{14}/`\u{11}iN\u{1d}\u{4}\u{1b}H\u{2}\u{f}]k@\0\0" }

  public static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData)

  public func _protobuf_messageStorage(accessToken: SwiftProtobuf._MessageStorageToken) -> AnyObject { _storage }

}
