// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/protobuf/compiler/plugin.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Protocol Buffers - Google's data interchange format
// Copyright 2008 Google Inc.  All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd

// Author: kenton@google.com (Kenton Varda)
//
// protoc (aka the Protocol Compiler) can be extended via plugins.  A plugin is
// just a program that reads a CodeGeneratorRequest from stdin and writes a
// CodeGeneratorResponse to stdout.
//
// Plugins written using C++ can use google/protobuf/compiler/plugin.h instead
// of dealing with the raw protocol defined here.
//
// A plugin executable needs only to be placed somewhere in the path.  The
// plugin should be named "protoc-gen-$NAME", and will then be used when the
// flag "--${NAME}_out" is passed to protoc.

@_spi(ForGeneratedCodeOnly) import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The version number of protocol compiler.
public struct Google_Protobuf_Compiler_Version: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var major: Int32 {
    get { _storage.value(at: 4, default: 0, hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: 4, to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `major` has been explicitly set.
  public var hasMajor: Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `major`. Subsequent reads from it will return its default value.
  public mutating func clearMajor() { _uniqueStorage().clearValue(at: 4, type: Int32.self, hasBit: (0, 1)) }

  public var minor: Int32 {
    get { _storage.value(at: 8, default: 0, hasBit: (0, 2)) }
    set { _uniqueStorage().updateValue(at: 8, to: newValue, willBeSet: true, hasBit: (0, 2)) }
  }
  /// Returns true if `minor` has been explicitly set.
  public var hasMinor: Bool { _storage.isPresent(hasBit: (0, 2)) }
  /// Clears the value of `minor`. Subsequent reads from it will return its default value.
  public mutating func clearMinor() { _uniqueStorage().clearValue(at: 8, type: Int32.self, hasBit: (0, 2)) }

  public var patch: Int32 {
    get { _storage.value(at: 12, default: 0, hasBit: (0, 4)) }
    set { _uniqueStorage().updateValue(at: 12, to: newValue, willBeSet: true, hasBit: (0, 4)) }
  }
  /// Returns true if `patch` has been explicitly set.
  public var hasPatch: Bool { _storage.isPresent(hasBit: (0, 4)) }
  /// Clears the value of `patch`. Subsequent reads from it will return its default value.
  public mutating func clearPatch() { _uniqueStorage().clearValue(at: 12, type: Int32.self, hasBit: (0, 4)) }

  /// A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
  /// be empty for mainline stable releases.
  public var suffix: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(16, 24), default: String(), hasBit: (0, 8)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(16, 24), to: newValue, willBeSet: true, hasBit: (0, 8)) }
  }
  /// Returns true if `suffix` has been explicitly set.
  public var hasSuffix: Bool { _storage.isPresent(hasBit: (0, 8)) }
  /// Clears the value of `suffix`. Subsequent reads from it will return its default value.
  public mutating func clearSuffix() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(16, 24), type: String.self, hasBit: (0, 8)) }

  public var unknownFields: SwiftProtobuf.UnknownStorage {
    get { _storage.unknownFields }
    _modify {
      _ = _uniqueStorage()
      yield &_storage.unknownFields
    }
  }

  public init() {}

  private var _storage = SwiftProtobuf._MessageStorage(schema: Self.messageSchema)
  private mutating func _uniqueStorage() -> SwiftProtobuf._MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  public mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf._MessageStorageToken) { _ = _uniqueStorage() }
  public func _protobuf_extensionStorageImpl() -> AnyObject { _storage.extensionStorage }
  public mutating func _protobuf_uniqueExtensionStorageImpl() -> AnyObject { _uniqueStorage().extensionStorage }
}

/// An encoded CodeGeneratorRequest is written to the plugin's stdin.
public struct Google_Protobuf_Compiler_CodeGeneratorRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The .proto files that were explicitly listed on the command-line.  The
  /// code generator should generate code only for these files.  Each file's
  /// descriptor will be included in proto_file, below.
  public var fileToGenerate: [String] {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(8, 4), hasBit: (0, 4)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(8, 4), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 4)) }
  }

  /// The generator parameter passed on the command-line.
  public var parameter: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(48, 24), default: String(), hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(48, 24), to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `parameter` has been explicitly set.
  public var hasParameter: Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `parameter`. Subsequent reads from it will return its default value.
  public mutating func clearParameter() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(48, 24), type: String.self, hasBit: (0, 1)) }

  /// FileDescriptorProtos for all files in files_to_generate and everything
  /// they import.  The files will appear in topological order, so each file
  /// appears before any file that imports it.
  ///
  /// Note: the files listed in files_to_generate will include runtime-retention
  /// options only, but all other files will include source-retention options.
  /// The source_file_descriptors field below is available in case you need
  /// source-retention options for files_to_generate.
  ///
  /// protoc guarantees that all proto_files will be written after
  /// the fields above, even though this is not technically guaranteed by the
  /// protobuf wire format.  This theoretically could allow a plugin to stream
  /// in the FileDescriptorProtos and handle them one by one rather than read
  /// the entire set into memory at once.  However, as of this writing, this
  /// is not similarly optimized on protoc's end -- it will store all fields in
  /// memory at once before sending them to the plugin.
  ///
  /// Type names of fields and extensions in the FileDescriptorProto are always
  /// fully qualified.
  public var protoFile: [SwiftProtobuf.Google_Protobuf_FileDescriptorProto] {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(24, 12), hasBit: (0, 8)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(24, 12), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 8)) }
  }

  /// File descriptors with all options, including source-retention options.
  /// These descriptors are only provided for the files listed in
  /// files_to_generate.
  public var sourceFileDescriptors: [SwiftProtobuf.Google_Protobuf_FileDescriptorProto] {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(32, 16), hasBit: (0, 16)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(32, 16), to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 16)) }
  }

  /// The version number of protocol compiler.
  public var compilerVersion: Google_Protobuf_Compiler_Version {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(16, 8), default: Google_Protobuf_Compiler_Version(), hasBit: (0, 2)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(16, 8), to: newValue, willBeSet: true, hasBit: (0, 2)) }
  }
  /// Returns true if `compilerVersion` has been explicitly set.
  public var hasCompilerVersion: Bool { _storage.isPresent(hasBit: (0, 2)) }
  /// Clears the value of `compilerVersion`. Subsequent reads from it will return its default value.
  public mutating func clearCompilerVersion() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(16, 8), type: Google_Protobuf_Compiler_Version.self, hasBit: (0, 2)) }

  public var unknownFields: SwiftProtobuf.UnknownStorage {
    get { _storage.unknownFields }
    _modify {
      _ = _uniqueStorage()
      yield &_storage.unknownFields
    }
  }

  public init() {}

  private var _storage = SwiftProtobuf._MessageStorage(schema: Self.messageSchema)
  private mutating func _uniqueStorage() -> SwiftProtobuf._MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  public mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf._MessageStorageToken) { _ = _uniqueStorage() }
  public func _protobuf_extensionStorageImpl() -> AnyObject { _storage.extensionStorage }
  public mutating func _protobuf_uniqueExtensionStorageImpl() -> AnyObject { _uniqueStorage().extensionStorage }
}

/// The plugin writes an encoded CodeGeneratorResponse to stdout.
public struct Google_Protobuf_Compiler_CodeGeneratorResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Error message.  If non-empty, code generation failed.  The plugin process
  /// should exit with status code zero even if it reports an error in this way.
  ///
  /// This should be used to indicate errors in .proto files which prevent the
  /// code generator from generating correct code.  Errors which indicate a
  /// problem in protoc itself -- such as the input CodeGeneratorRequest being
  /// unparseable -- should be reported by writing a message to stderr and
  /// exiting with a non-zero status code.
  public var error: String {
    get { _storage.value(at: SwiftProtobuf._fieldOffset(32, 36), default: String(), hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(32, 36), to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(32, 36), type: String.self, hasBit: (0, 1)) }

  /// A bitmask of supported features that the code generator supports.
  /// This is a bitwise "or" of values from the Feature enum.
  public var supportedFeatures: UInt64 {
    get { _storage.value(at: 16, default: 0, hasBit: (0, 2)) }
    set { _uniqueStorage().updateValue(at: 16, to: newValue, willBeSet: true, hasBit: (0, 2)) }
  }
  /// Returns true if `supportedFeatures` has been explicitly set.
  public var hasSupportedFeatures: Bool { _storage.isPresent(hasBit: (0, 2)) }
  /// Clears the value of `supportedFeatures`. Subsequent reads from it will return its default value.
  public mutating func clearSupportedFeatures() { _uniqueStorage().clearValue(at: 16, type: UInt64.self, hasBit: (0, 2)) }

  /// The minimum edition this plugin supports.  This will be treated as an
  /// Edition enum, but we want to allow unknown values.  It should be specified
  /// according the edition enum value, *not* the edition number.  Only takes
  /// effect for plugins that have FEATURE_SUPPORTS_EDITIONS set.
  public var minimumEdition: Int32 {
    get { _storage.value(at: 4, default: 0, hasBit: (0, 4)) }
    set { _uniqueStorage().updateValue(at: 4, to: newValue, willBeSet: true, hasBit: (0, 4)) }
  }
  /// Returns true if `minimumEdition` has been explicitly set.
  public var hasMinimumEdition: Bool { _storage.isPresent(hasBit: (0, 4)) }
  /// Clears the value of `minimumEdition`. Subsequent reads from it will return its default value.
  public mutating func clearMinimumEdition() { _uniqueStorage().clearValue(at: 4, type: Int32.self, hasBit: (0, 4)) }

  /// The maximum edition this plugin supports.  This will be treated as an
  /// Edition enum, but we want to allow unknown values.  It should be specified
  /// according the edition enum value, *not* the edition number.  Only takes
  /// effect for plugins that have FEATURE_SUPPORTS_EDITIONS set.
  public var maximumEdition: Int32 {
    get { _storage.value(at: 8, default: 0, hasBit: (0, 8)) }
    set { _uniqueStorage().updateValue(at: 8, to: newValue, willBeSet: true, hasBit: (0, 8)) }
  }
  /// Returns true if `maximumEdition` has been explicitly set.
  public var hasMaximumEdition: Bool { _storage.isPresent(hasBit: (0, 8)) }
  /// Clears the value of `maximumEdition`. Subsequent reads from it will return its default value.
  public mutating func clearMaximumEdition() { _uniqueStorage().clearValue(at: 8, type: Int32.self, hasBit: (0, 8)) }

  public var file: [Google_Protobuf_Compiler_CodeGeneratorResponse.File] {
    get { _storage.value(at: 24, hasBit: (0, 16)) }
    set { _uniqueStorage().updateValue(at: 24, to: newValue, willBeSet: !newValue.isEmpty, hasBit: (0, 16)) }
  }

  public var unknownFields: SwiftProtobuf.UnknownStorage {
    get { _storage.unknownFields }
    _modify {
      _ = _uniqueStorage()
      yield &_storage.unknownFields
    }
  }

  /// Sync with code_generator.h.
  public enum Feature: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case none = 0
    case proto3Optional = 1
    case supportsEditions = 2

    public init() {
      self = .none
    }

  }

  /// Represents a single generated file.
  public struct File: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The file name, relative to the output directory.  The name must not
    /// contain "." or ".." components and must be relative, not be absolute (so,
    /// the file cannot lie outside the output directory).  "/" must be used as
    /// the path separator, not "\".
    ///
    /// If the name is omitted, the content will be appended to the previous
    /// file.  This allows the generator to break large files into small chunks,
    /// and allows the generated text to be streamed back to protoc so that large
    /// files need not reside completely in memory at one time.  Note that as of
    /// this writing protoc does not optimize for this -- it will read the entire
    /// CodeGeneratorResponse before writing files to disk.
    public var name: String {
      get { _storage.value(at: SwiftProtobuf._fieldOffset(16, 12), default: String(), hasBit: (0, 1)) }
      set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(16, 12), to: newValue, willBeSet: true, hasBit: (0, 1)) }
    }
    /// Returns true if `name` has been explicitly set.
    public var hasName: Bool { _storage.isPresent(hasBit: (0, 1)) }
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    public mutating func clearName() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(16, 12), type: String.self, hasBit: (0, 1)) }

    /// If non-empty, indicates that the named file should already exist, and the
    /// content here is to be inserted into that file at a defined insertion
    /// point.  This feature allows a code generator to extend the output
    /// produced by another code generator.  The original generator may provide
    /// insertion points by placing special annotations in the file that look
    /// like:
    ///   @@protoc_insertion_point(NAME)
    /// The annotation can have arbitrary text before and after it on the line,
    /// which allows it to be placed in a comment.  NAME should be replaced with
    /// an identifier naming the point -- this is what other generators will use
    /// as the insertion_point.  Code inserted at this point will be placed
    /// immediately above the line containing the insertion point (thus multiple
    /// insertions to the same point will come out in the order they were added).
    /// The double-@ is intended to make it unlikely that the generated code
    /// could contain things that look like insertion points by accident.
    ///
    /// For example, the C++ code generator places the following line in the
    /// .pb.h files that it generates:
    ///   // @@protoc_insertion_point(namespace_scope)
    /// This line appears within the scope of the file's package namespace, but
    /// outside of any particular class.  Another plugin can then specify the
    /// insertion_point "namespace_scope" to generate additional classes or
    /// other declarations that should be placed in this scope.
    ///
    /// Note that if the line containing the insertion point begins with
    /// whitespace, the same whitespace will be added to every line of the
    /// inserted text.  This is useful for languages like Python, where
    /// indentation matters.  In these languages, the insertion point comment
    /// should be indented the same amount as any inserted code will need to be
    /// in order to work correctly in that context.
    ///
    /// The code generator that generates the initial file and the one which
    /// inserts into it must both run as part of a single invocation of protoc.
    /// Code generators are executed in the order in which they appear on the
    /// command line.
    ///
    /// If |insertion_point| is present, |name| must also be present.
    public var insertionPoint: String {
      get { _storage.value(at: SwiftProtobuf._fieldOffset(32, 24), default: String(), hasBit: (0, 2)) }
      set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(32, 24), to: newValue, willBeSet: true, hasBit: (0, 2)) }
    }
    /// Returns true if `insertionPoint` has been explicitly set.
    public var hasInsertionPoint: Bool { _storage.isPresent(hasBit: (0, 2)) }
    /// Clears the value of `insertionPoint`. Subsequent reads from it will return its default value.
    public mutating func clearInsertionPoint() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(32, 24), type: String.self, hasBit: (0, 2)) }

    /// The file contents.
    public var content: String {
      get { _storage.value(at: SwiftProtobuf._fieldOffset(48, 36), default: String(), hasBit: (0, 4)) }
      set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(48, 36), to: newValue, willBeSet: true, hasBit: (0, 4)) }
    }
    /// Returns true if `content` has been explicitly set.
    public var hasContent: Bool { _storage.isPresent(hasBit: (0, 4)) }
    /// Clears the value of `content`. Subsequent reads from it will return its default value.
    public mutating func clearContent() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(48, 36), type: String.self, hasBit: (0, 4)) }

    /// Information describing the file content being inserted. If an insertion
    /// point is used, this information will be appropriately offset and inserted
    /// into the code generation metadata for the generated files.
    public var generatedCodeInfo: SwiftProtobuf.Google_Protobuf_GeneratedCodeInfo {
      get { _storage.value(at: SwiftProtobuf._fieldOffset(8, 4), default: SwiftProtobuf.Google_Protobuf_GeneratedCodeInfo(), hasBit: (0, 8)) }
      set { _uniqueStorage().updateValue(at: SwiftProtobuf._fieldOffset(8, 4), to: newValue, willBeSet: true, hasBit: (0, 8)) }
    }
    /// Returns true if `generatedCodeInfo` has been explicitly set.
    public var hasGeneratedCodeInfo: Bool { _storage.isPresent(hasBit: (0, 8)) }
    /// Clears the value of `generatedCodeInfo`. Subsequent reads from it will return its default value.
    public mutating func clearGeneratedCodeInfo() { _uniqueStorage().clearValue(at: SwiftProtobuf._fieldOffset(8, 4), type: SwiftProtobuf.Google_Protobuf_GeneratedCodeInfo.self, hasBit: (0, 8)) }

    public var unknownFields: SwiftProtobuf.UnknownStorage {
      get { _storage.unknownFields }
      _modify {
        _ = _uniqueStorage()
        yield &_storage.unknownFields
      }
    }

    public init() {}

    private var _storage = SwiftProtobuf._MessageStorage(schema: Self.messageSchema)
    private mutating func _uniqueStorage() -> SwiftProtobuf._MessageStorage {
      if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
      return _storage
    }
    public mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf._MessageStorageToken) { _ = _uniqueStorage() }
    public func _protobuf_extensionStorageImpl() -> AnyObject { _storage.extensionStorage }
    public mutating func _protobuf_uniqueExtensionStorageImpl() -> AnyObject { _uniqueStorage().extensionStorage }
  }

  public init() {}

  private var _storage = SwiftProtobuf._MessageStorage(schema: Self.messageSchema)
  private mutating func _uniqueStorage() -> SwiftProtobuf._MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  public mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf._MessageStorageToken) { _ = _uniqueStorage() }
  public func _protobuf_extensionStorageImpl() -> AnyObject { _storage.extensionStorage }
  public mutating func _protobuf_uniqueExtensionStorageImpl() -> AnyObject { _uniqueStorage().extensionStorage }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.protobuf.compiler"

extension Google_Protobuf_Compiler_Version: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".Version"
  #if _pointerBitWidth(_64)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0 \0\0\u{4}\0\0\0\0\0\u{4}\0\0\u{5}\0\0\u{1}\0\0\0\0\u{4}\0\0\0\0\0\0\u{5}\u{2}\0\0\0\0\u{8}\0\0\u{1}\0\0\0\u{5}\u{3}\0\0\0\0\u{c}\0\0\u{2}\0\0\0\u{5}\u{4}\0\0\0\0\u{10}\0\0\u{3}\0\0\0\u{9} \0google.protobuf.compiler.Version" }
  #elseif _pointerBitWidth(_32)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0$\0\0\u{4}\0\0\0\0\0\u{4}\0\0\u{5}\0\0\u{1}\0\0\0\0\u{4}\0\0\0\0\0\0\u{5}\u{2}\0\0\0\0\u{8}\0\0\u{1}\0\0\0\u{5}\u{3}\0\0\0\0\u{c}\0\0\u{2}\0\0\0\u{5}\u{4}\0\0\0\0\u{18}\0\0\u{3}\0\0\0\u{9} \0google.protobuf.compiler.Version" }
  #else
    #error("Unsupported platform")
  #endif
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_reflectionData: StaticString { "h\0\0\0p\u{1}4\u{4}\u{f}K\0)h\0]8Gll_\u{7f}7ty\u{5}V\u{7}\u{5}'\u{1e}D\\K>\u{1}qu\u{3}\u{1e}!E>6{F\u{2}\u{3}' \u{16}@P\u{7}\u{4}#{B\u{b}D\u{1a}cN\tuk\u{1c}N\u{2}s<{~\0\0" }

  public static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData)
  public var messageSchema: SwiftProtobuf.MessageSchema { Self.messageSchema }

  public func _protobuf_messageStorage(accessToken: SwiftProtobuf._MessageStorageToken) -> AnyObject { _storage }

}

extension Google_Protobuf_Compiler_CodeGeneratorRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".CodeGeneratorRequest"
  #if _pointerBitWidth(_64)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0@\0\0\u{5}\0\0\0\0\0\u{2}\0\0\u{4}\0\0\u{1}\0\0\0\u{2}\u{8}\0\0\u{2}\0\0\0\u{9}\u{2}\0\0\0\00\0\0\0\0\0\0\u{9}\u{3}\0\0\0\0\u{10}\0\0\u{1}\0\u{1}\0\u{b}\u{f}\0\0\0\u{2}\u{18}\0\0\u{3}\0\u{2}\0\u{b}\u{11}\0\0\0\u{2} \0\0\u{4}\0\u{2}\0\u{b}-\0google.protobuf.compiler.CodeGeneratorRequest" }
  #elseif _pointerBitWidth(_32)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0$\0\0\u{5}\0\0\0\0\0\u{2}\0\0\u{4}\0\0\u{1}\0\0\0\u{2}\u{4}\0\0\u{2}\0\0\0\u{9}\u{2}\0\0\0\0\u{18}\0\0\0\0\0\0\u{9}\u{3}\0\0\0\0\u{8}\0\0\u{1}\0\u{1}\0\u{b}\u{f}\0\0\0\u{2}\u{c}\0\0\u{3}\0\u{2}\0\u{b}\u{11}\0\0\0\u{2}\u{10}\0\0\u{4}\0\u{2}\0\u{b}-\0google.protobuf.compiler.CodeGeneratorRequest" }
  #else
    #error("Unsupported platform")
  #endif
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_reflectionData: StaticString { "\u{c}\u{2}\0\0\0_\u{10}c=ZOJXA\u{17}SCZ?\u{19}\"x<DoA\u{15}OG\u{17}kQ/?|@5Mxs(\rYDU&s\u{11}~j\u{4}:\u{7f}Q\u{15}\u{7f}\u{2}lUF^Q`tk\\3\n~\0\u{5}$[\u{6}\u{1c}&H\u{1f}N\u{5}W'\u{6}g^),\rSm\u{14}}vI;*Wk}(\u{10}\u{4}|\u{7f}R\\\r`m\u{19}\u{16}G(\\{!&#@M\u{2}G\u{17}w\u{8}(a&^#?U\\`[%\u{12}\u{17}\u{4}y\u{15}(\u{1c}\u{16}1c1CW\05e\0\u{7}\u{10}K#:B\u{12}6.u\u{10}\u{7}\0\0" }

  public static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, performNontrivialFieldOperation: _protobuf_performNontrivialFieldOperation, performOnSubmessageStorage: _protobuf_performOnSubmessageStorage, performOnRawEnumValues: _protobuf_performOnRawEnumValues, mapEntrySchema: _protobuf_mapEntrySchema, performOnMapEntry: _protobuf_performOnMapEntry)

  private static func _protobuf_performNontrivialFieldOperation(for token: SwiftProtobuf.MessageSchema.TrampolineToken, operation: SwiftProtobuf.NontrivialFieldOperation, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage) -> Bool {
    switch token.index {
    case 1: return storage.performNontrivialFieldOperation(operation, field: field, type: Google_Protobuf_Compiler_Version.self)
    case 2: return storage.performNontrivialFieldOperation(operation, field: field, type: [SwiftProtobuf.Google_Protobuf_FileDescriptorProto].self)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnSubmessageStorage(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    case 1: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: Google_Protobuf_Compiler_Version.self, perform: perform)
    case 2: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: [SwiftProtobuf.Google_Protobuf_FileDescriptorProto].self, perform: perform)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnRawEnumValues(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf.EnumSchema, inout Int32) throws -> Bool, onInvalidValue: (Int32) throws -> Void) throws {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_mapEntrySchema(for token: SwiftProtobuf.MessageSchema.TrampolineToken) -> SwiftProtobuf.MessageSchema {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnMapEntry(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, workingSpace: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, deterministicOrdering: Bool, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }
  public var messageSchema: SwiftProtobuf.MessageSchema { Self.messageSchema }

  public func _protobuf_messageStorage(accessToken: SwiftProtobuf._MessageStorageToken) -> AnyObject { _storage }

  public var isInitialized: Bool {
    return _storage.isInitialized
  }

}

extension Google_Protobuf_Compiler_CodeGeneratorResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".CodeGeneratorResponse"
  #if _pointerBitWidth(_64)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\00\0\0\u{5}\0\0\0\0\0\u{4}\0\0\u{5}\0\0\u{1}\0\0\0\0 \0\0\0\0\0\0\u{9}\u{2}\0\0\0\0\u{10}\0\0\u{1}\0\0\0\u{4}\u{3}\0\0\0\0\u{4}\0\0\u{2}\0\0\0\u{5}\u{4}\0\0\0\0\u{8}\0\0\u{3}\0\0\0\u{5}\u{f}\0\0\0\u{2}\u{18}\0\0\u{4}\0\u{1}\0\u{b}.\0google.protobuf.compiler.CodeGeneratorResponse" }
  #elseif _pointerBitWidth(_32)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\00\0\0\u{5}\0\0\0\0\0\u{4}\0\0\u{5}\0\0\u{1}\0\0\0\0$\0\0\0\0\0\0\u{9}\u{2}\0\0\0\0\u{10}\0\0\u{1}\0\0\0\u{4}\u{3}\0\0\0\0\u{4}\0\0\u{2}\0\0\0\u{5}\u{4}\0\0\0\0\u{8}\0\0\u{3}\0\0\0\u{5}\u{f}\0\0\0\u{2}\u{18}\0\0\u{4}\0\u{1}\0\u{b}.\0google.protobuf.compiler.CodeGeneratorResponse" }
  #else
    #error("Unsupported platform")
  #endif
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_reflectionData: StaticString { "d\u{1}\0\00?$\\a[o\u{5}J\u{3}\u{1f}DR6kE>1YrO&=\u{7f}.LwFb\"\u{1c}\0({K>\u{1c}\rQxw\\b_']`4\u{3}!Wa(VwWj\u{19}\u{c}$!,q\u{1b}\u{1a}'1BE*S\u{6}NP\"l\u{7}s3h[TB\u{17}FS'7bLq*\u{1d}\u{e}F[\u{14}*d8-ocV2\u{1f}\u{13}[RP&\u{e}KQ.\\#L-zu1\u{e}\u{11}\u{14}Qn!\u{7}\0" }

  public static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, performNontrivialFieldOperation: _protobuf_performNontrivialFieldOperation, performOnSubmessageStorage: _protobuf_performOnSubmessageStorage, performOnRawEnumValues: _protobuf_performOnRawEnumValues, mapEntrySchema: _protobuf_mapEntrySchema, performOnMapEntry: _protobuf_performOnMapEntry)

  private static func _protobuf_performNontrivialFieldOperation(for token: SwiftProtobuf.MessageSchema.TrampolineToken, operation: SwiftProtobuf.NontrivialFieldOperation, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage) -> Bool {
    switch token.index {
    case 1: return storage.performNontrivialFieldOperation(operation, field: field, type: [Google_Protobuf_Compiler_CodeGeneratorResponse.File].self)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnSubmessageStorage(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    case 1: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: [Google_Protobuf_Compiler_CodeGeneratorResponse.File].self, perform: perform)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnRawEnumValues(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf.EnumSchema, inout Int32) throws -> Bool, onInvalidValue: (Int32) throws -> Void) throws {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_mapEntrySchema(for token: SwiftProtobuf.MessageSchema.TrampolineToken) -> SwiftProtobuf.MessageSchema {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnMapEntry(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, workingSpace: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, deterministicOrdering: Bool, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }
  public var messageSchema: SwiftProtobuf.MessageSchema { Self.messageSchema }

  public func _protobuf_messageStorage(accessToken: SwiftProtobuf._MessageStorageToken) -> AnyObject { _storage }

}

extension Google_Protobuf_Compiler_CodeGeneratorResponse.Feature {
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_enumSchemaString: StaticString { "\0\u{3}\0\0\0\06\0google.protobuf.compiler.CodeGeneratorResponse.Feature" }
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_reflectionData: StaticString { "|\0\0\0`\u{b}ez\u{5}\u{6}vB2sl.2R*{\u{4}\u{7f}\u{15}!\\z`QEYf\u{11};Om\n`lX\u{11}\u{7f}p\u{2}56QN\nKpO1n:+l 4I\u{4} 0b<k3\u{17}?\"h\u{19}WPg\u{13}\u{18}F\u{17}\0\0" }
  public static let enumSchema = SwiftProtobuf.EnumSchema(schema: _protobuf_enumSchemaString, reflection: _protobuf_reflectionData)
}

extension Google_Protobuf_Compiler_CodeGeneratorResponse.File: SwiftProtobuf.Message {
  public static let protoMessageName: String = Google_Protobuf_Compiler_CodeGeneratorResponse.protoMessageName + ".File"
  #if _pointerBitWidth(_64)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\0@\0\0\u{4}\0\0\0\0\0\u{4}\0\0\u{3}\0\0\u{1}\0\0\0\0\u{10}\0\0\0\0\0\0\u{9}\u{2}\0\0\0\0 \0\0\u{1}\0\0\0\u{9}\u{f}\0\0\0\00\0\0\u{2}\0\0\0\u{9}\u{10}\0\0\0\0\u{8}\0\0\u{3}\0\u{1}\0\u{b}3\0google.protobuf.compiler.CodeGeneratorResponse.File" }
  #elseif _pointerBitWidth(_32)
    @_alwaysEmitIntoClient @inline(__always)
    private static var _protobuf_messageSchemaString: StaticString { "\00\0\0\u{4}\0\0\0\0\0\u{4}\0\0\u{3}\0\0\u{1}\0\0\0\0\u{c}\0\0\0\0\0\0\u{9}\u{2}\0\0\0\0\u{18}\0\0\u{1}\0\0\0\u{9}\u{f}\0\0\0\0$\0\0\u{2}\0\0\0\u{9}\u{10}\0\0\0\0\u{4}\0\0\u{3}\0\u{1}\0\u{b}3\0google.protobuf.compiler.CodeGeneratorResponse.File" }
  #else
    #error("Unsupported platform")
  #endif
  @_alwaysEmitIntoClient @inline(__always)
  private static var _protobuf_reflectionData: StaticString { "0\u{1}\0\0 \u{1f}1v\u{15}Z[,EC\u{1f}Zbf;\u{7}\u{1a}\u{17}JJ\u{8}GSE*zqiz}\u{3}GXWr\u{7f}t\u{1}:u\u{1}v6}w\u{8})\u{1a}U<A\u{c}n(B)\u{1a}R^\u{e}\u{11}{+\u{1c}\u{5}4\u{8};\u{1}hu\u{1e}\u{1f}sx\u{b}[NtP0\u{1f}2$THA6(\u{5}\np&P_\u{1c}V\t|81\u{1a}#Hm{D\u{1f}\u{1d} Z\u{7f}\u{18}\n\0" }

  public static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, performNontrivialFieldOperation: _protobuf_performNontrivialFieldOperation, performOnSubmessageStorage: _protobuf_performOnSubmessageStorage, performOnRawEnumValues: _protobuf_performOnRawEnumValues, mapEntrySchema: _protobuf_mapEntrySchema, performOnMapEntry: _protobuf_performOnMapEntry)

  private static func _protobuf_performNontrivialFieldOperation(for token: SwiftProtobuf.MessageSchema.TrampolineToken, operation: SwiftProtobuf.NontrivialFieldOperation, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage) -> Bool {
    switch token.index {
    case 1: return storage.performNontrivialFieldOperation(operation, field: field, type: SwiftProtobuf.Google_Protobuf_GeneratedCodeInfo.self)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnSubmessageStorage(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    case 1: return try storage.performOnSubmessageStorage(of: field, operation: operation, type: SwiftProtobuf.Google_Protobuf_GeneratedCodeInfo.self, perform: perform)
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnRawEnumValues(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, perform: (SwiftProtobuf.EnumSchema, inout Int32) throws -> Bool, onInvalidValue: (Int32) throws -> Void) throws {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_mapEntrySchema(for token: SwiftProtobuf.MessageSchema.TrampolineToken) -> SwiftProtobuf.MessageSchema {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }

  private static func _protobuf_performOnMapEntry(for token: SwiftProtobuf.MessageSchema.TrampolineToken, field: SwiftProtobuf.FieldSchema, storage: SwiftProtobuf._MessageStorage, workingSpace: SwiftProtobuf._MessageStorage, operation: SwiftProtobuf.TrampolineFieldOperation, deterministicOrdering: Bool, perform: (SwiftProtobuf._MessageStorage) throws -> Bool) throws -> Bool {
    switch token.index {
    default: preconditionFailure("invalid trampoline token; this is a generator bug")
    }
  }
  public var messageSchema: SwiftProtobuf.MessageSchema { Self.messageSchema }

  public func _protobuf_messageStorage(accessToken: SwiftProtobuf._MessageStorageToken) -> AnyObject { _storage }

}
