// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: unittest_json_enumvalue_custom_string.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Protos/unittest_swift_enum_optional_default.proto - test proto
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
// -----------------------------------------------------------------------------
///
/// Test support for the option for enum value custom json values.
///
// -----------------------------------------------------------------------------

@_spi(ForGeneratedCodeOnly) import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum SwiftProtoTesting_EnumValueJsonString_EnumCustomJSONString: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Swift.Int
  case unknown // = 0
  case somethingSpecial // = 1
  case normal // = 2
  case quoted // = 3
  case blank // = 4
  case escapes // = 5
  case six // = 6
  static let somethingSpecialAlias = somethingSpecial
  case UNRECOGNIZED(Swift.Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Swift.Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .somethingSpecial
    case 2: self = .normal
    case 3: self = .quoted
    case 4: self = .blank
    case 5: self = .escapes
    case 6: self = .six
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Swift.Int {
    switch self {
    case .unknown: return 0
    case .somethingSpecial: return 1
    case .normal: return 2
    case .quoted: return 3
    case .blank: return 4
    case .escapes: return 5
    case .six: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [SwiftProtoTesting_EnumValueJsonString_EnumCustomJSONString] = [
    .unknown,
    .somethingSpecial,
    .normal,
    .quoted,
    .blank,
    .escapes,
    .six,
  ]

}

struct SwiftProtoTesting_EnumValueJsonString_EnumCustomJSONStringsMessage: @unchecked Swift.Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var testCase: SwiftProtoTesting_EnumValueJsonString_EnumCustomJSONString {
    get { _storage.value(at: 4, default: .unknown, hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: 4, to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `testCase` has been explicitly set.
  var hasTestCase: Swift.Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `testCase`. Subsequent reads from it will return its default value.
  mutating func clearTestCase() { _uniqueStorage().clearValue(at: 4, type: SwiftProtoTesting_EnumValueJsonString_EnumCustomJSONString.self, hasBit: (0, 1)) }

  init() { self._storage = SwiftProtobuf.MessageStorage(schema: Self.messageSchema) }

  private var _storage: SwiftProtobuf.MessageStorage
  private mutating func _uniqueStorage() -> SwiftProtobuf.MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf.MessageStorageToken) { _ = _uniqueStorage() }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "swift_proto_testing.enum_value_json_string"

extension SwiftProtoTesting_EnumValueJsonString_EnumCustomJSONString {
  private static let _protobuf_enumSchemaString: Swift.StaticString = "\0\u{7}\0\0\0\0?\0swift_proto_testing.enum_value_json_string.EnumCustomJSONString"
  private static let _protobuf_reflectionData: Swift.StaticString = "\u{1c}\u{3}\0\0 ?^t.9M\u{14}'Ij\\hZ\u{c}\u{1d}ub2y49k\u{1e}\u{3}\"gpp\u{17}Lf`\u{5}U\u{3}<)*`V\te\u{7f}HQ\u{1f}!\u{5}9>x\u{11}\n/(tZ2wOZ\u{1e}9\u{16}\u{1b} \u{1d}e\u{4}iGlF|vT>ncKl\u{10}\"\u{1c}_bFp8N\u{1d}#c9\u{12}U\u{6}&@X\u{16}\u{10}W\u{1f}`Yzy.~*)'mg\u{2}\u{15}*\u{1f}\u{6}hW1b\u{11}Tr\u{1e}k,+/Z\u{7}t'\u{19}M4Ws\u{10}\u{13}n\u{11}ab\u{14}6\u{12}lNk\u{7f}|\u{15}{\u{1d}I\u{17}]\u{7f}\u{8}\u{1}`4\u{1d}\u{10}\u{14}\\jX \u{3}\0\0"
  static let enumSchema = SwiftProtobuf.EnumSchema(schema: _protobuf_enumSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.EnumWitnesses<Self>.perform)
}

extension SwiftProtoTesting_EnumValueJsonString_EnumCustomJSONStringsMessage: SwiftProtobuf.GeneratedMessage {
  #if _pointerBitWidth(_64)
    private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\u{8}\0\0\u{1}\0\0\0\0\0\u{1}\0\0\u{2}\0\0\u{8}\0\0\u{1}\0\0\0\0\u{4}\0\0\0\0\u{1}\0\u{e}G\0swift_proto_testing.enum_value_json_string.EnumCustomJSONStringsMessage"
  #elseif _pointerBitWidth(_32)
    private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\u{8}\0\0\u{1}\0\0\0\0\0\u{1}\0\0\u{2}\0\0\u{8}\0\0\u{1}\0\0\0\0\u{4}\0\0\0\0\u{1}\0\u{e}G\0swift_proto_testing.enum_value_json_string.EnumCustomJSONStringsMessage"
  #else
    #error("Unsupported platform")
  #endif
  private static let _protobuf_reflectionData: Swift.StaticString = "<\0\0\0@~K#:MIJww:\u{16}+|8_X\u{1a}|hIl\rET8\u{2}2*nI\u{19}4`6\u{16} \u{16}NV\n\0"

  static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.MessageWitnesses<Self>.perform, submessageOrEnumResolver: _protobuf_resolveSubmessageOrEnum)

  private static func _protobuf_resolveSubmessageOrEnum(for token: SwiftProtobuf.SubmessageOrEnumToken) -> SwiftProtobuf.SubmessageOrEnumSchema {
    switch token.index {
    case 1: return .enum(SwiftProtoTesting_EnumValueJsonString_EnumCustomJSONString.enumSchema)
    default: preconditionFailure("invalid submessage/enum token; this is a generator bug")
    }
  }

  func _protobuf_messageStorage(accessToken: SwiftProtobuf.MessageStorageToken) -> Swift.AnyObject { _storage }

}
