// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/protobuf/test_protos/abseil_flag_test.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

@_spi(ForGeneratedCodeOnly) import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Proto2Unittest_OpenEnumForFlagTest: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Swift.Int
  case `default` // = 0
  case UNRECOGNIZED(Swift.Int)

  init() {
    self = .default
  }

  init?(rawValue: Swift.Int) {
    switch rawValue {
    case 0: self = .default
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Swift.Int {
    switch self {
    case .default: return 0
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Proto2Unittest_OpenEnumForFlagTest] = [
    .default,
  ]

}

nonisolated struct Proto2Unittest_AbseilFlagTestProto: @unchecked Swift.Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var i: Int32 {
    get { _storage.value(at: 4, default: 0, hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: 4, to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `i` has been explicitly set.
  var hasI: Swift.Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `i`. Subsequent reads from it will return its default value.
  mutating func clearI() { _uniqueStorage().clearValue(at: 4, type: Int32.self, hasBit: (0, 1)) }

  var e: Proto2Unittest_OpenEnumForFlagTest {
    get { _storage.value(at: 8, default: .default, hasBit: (0, 2)) }
    set { _uniqueStorage().updateValue(at: 8, to: newValue, willBeSet: true, hasBit: (0, 2)) }
  }
  /// Returns true if `e` has been explicitly set.
  var hasE: Swift.Bool { _storage.isPresent(hasBit: (0, 2)) }
  /// Clears the value of `e`. Subsequent reads from it will return its default value.
  mutating func clearE() { _uniqueStorage().clearValue(at: 8, type: Proto2Unittest_OpenEnumForFlagTest.self, hasBit: (0, 2)) }

  init() { self._storage = SwiftProtobuf.MessageStorage(schema: Self.messageSchema) }

  private var _storage: SwiftProtobuf.MessageStorage
  private mutating func _uniqueStorage() -> SwiftProtobuf.MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf.MessageStorageToken) { _ = _uniqueStorage() }
}

nonisolated struct Proto2Unittest_MessageWithConflictingFlagPrefixes: @unchecked Swift.Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var text: Int32 {
    get { _storage.value(at: 4, default: 0, hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: 4, to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `text` has been explicitly set.
  var hasText: Swift.Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `text`. Subsequent reads from it will return its default value.
  mutating func clearText() { _uniqueStorage().clearValue(at: 4, type: Int32.self, hasBit: (0, 1)) }

  var base64Text: Int32 {
    get { _storage.value(at: 8, default: 0, hasBit: (0, 2)) }
    set { _uniqueStorage().updateValue(at: 8, to: newValue, willBeSet: true, hasBit: (0, 2)) }
  }
  /// Returns true if `base64Text` has been explicitly set.
  var hasBase64Text: Swift.Bool { _storage.isPresent(hasBit: (0, 2)) }
  /// Clears the value of `base64Text`. Subsequent reads from it will return its default value.
  mutating func clearBase64Text() { _uniqueStorage().clearValue(at: 8, type: Int32.self, hasBit: (0, 2)) }

  var base64Serialized: Int32 {
    get { _storage.value(at: 12, default: 0, hasBit: (0, 4)) }
    set { _uniqueStorage().updateValue(at: 12, to: newValue, willBeSet: true, hasBit: (0, 4)) }
  }
  /// Returns true if `base64Serialized` has been explicitly set.
  var hasBase64Serialized: Swift.Bool { _storage.isPresent(hasBit: (0, 4)) }
  /// Clears the value of `base64Serialized`. Subsequent reads from it will return its default value.
  mutating func clearBase64Serialized() { _uniqueStorage().clearValue(at: 12, type: Int32.self, hasBit: (0, 4)) }

  init() { self._storage = SwiftProtobuf.MessageStorage(schema: Self.messageSchema) }

  private var _storage: SwiftProtobuf.MessageStorage
  private mutating func _uniqueStorage() -> SwiftProtobuf.MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf.MessageStorageToken) { _ = _uniqueStorage() }
}

// MARK: - Extension support defined in abseil_flag_test.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

nonisolated extension Proto2Unittest_AbseilFlagTestProto {

  var Proto2Unittest_AbseilFlagTestProto_ext: Int32 {
    get { _protobuf_extensionStorage().value(of: Proto2Unittest_AbseilFlagTestProto.Extensions.ext, default: 0) }
    set { _protobuf_uniqueExtensionStorage().updateValue(of: Proto2Unittest_AbseilFlagTestProto.Extensions.ext, to: newValue) }
  }
  /// Returns true if extension `Proto2Unittest_AbseilFlagTestProto.Extensions.ext`
  /// has been explicitly set.
  var hasProto2Unittest_AbseilFlagTestProto_ext: Bool { _protobuf_extensionStorage().hasValue(for: Proto2Unittest_AbseilFlagTestProto.Extensions.ext) }
  /// Clears the value of extension `Proto2Unittest_AbseilFlagTestProto.Extensions.ext`.
  /// Subsequent reads from it will return its default value.
  mutating func clearProto2Unittest_AbseilFlagTestProto_ext() { _protobuf_uniqueExtensionStorage().clearValue(of: Proto2Unittest_AbseilFlagTestProto.Extensions.ext, type: Int32.self) }

}

// MARK: - File's ExtensionMap: Proto2Unittest_AbseilFlagTest_Extensions

/// A `SwiftProtobuf.ExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used in parsing, or it can be combined with other
/// `SwiftProtobuf.ExtensionMap`s to create a larger `SwiftProtobuf.ExtensionMap`.
nonisolated let Proto2Unittest_AbseilFlagTest_Extensions: SwiftProtobuf.ExtensionMap = [
  Proto2Unittest_AbseilFlagTestProto.Extensions.ext
]

// Extension Objects - The only reason these might be needed is when manually
// constructing an `ExtensionMap`. Otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

nonisolated extension Proto2Unittest_AbseilFlagTestProto {
  enum Extensions {
    static let ext = SwiftProtobuf.ExtensionSchema(
      schema: "\0h\u{7}\0\0\u{10}\0\0\0\0\0\0\0\u{5}'\0proto2_unittest.AbseilFlagTestProto.ext",
      extendedMessageResolver: { Proto2Unittest_AbseilFlagTestProto.messageSchema }
      )
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension Proto2Unittest_OpenEnumForFlagTest {
  private static let _protobuf_enumSchemaString: Swift.StaticString = "\0\u{1}\0\0\0\0#\0proto2_unittest.OpenEnumForFlagTest"
  private static let _protobuf_reflectionData: Swift.StaticString = "@\0\0\0\u{10}\u{7f}Bo\r\u{7}&pm\u{e}\u{6}8ny'B\u{3}D\0sHJ3F.7\u{1d}\u{5}7QO\u{5}W\u{7}W\u{6}S\u{7f}7)\u{1b}<?\u{7f}\0\0"
  static let enumSchema = SwiftProtobuf.EnumSchema(schema: _protobuf_enumSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.EnumWitnesses<Self>.perform)
}

nonisolated extension Proto2Unittest_AbseilFlagTestProto: SwiftProtobuf.GeneratedMessage {
  private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\u{c}\0 \u{2}\0\0\0\0\0\u{2}\0\0\u{2}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\u{1}\0\0\0\0\u{4}\0\0\0\0\0\0\u{5}d\0\0\0\0\u{8}\0\0\u{1}\0\u{1}\0\u{e}#\0proto2_unittest.AbseilFlagTestProto"
  private static let _protobuf_reflectionData: Swift.StaticString = "4\0\0\0@\u{1a}o+%Jl1\u{1f}\u{2}d\u{b}\u{1d}X\05w;\u{17}02PxKv|5u\u{19}a\u{1e}L\u{5}\0"

  static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.MessageWitnesses<Self>.perform, submessageOrEnumResolver: _protobuf_resolveSubmessageOrEnum)

  private static func _protobuf_resolveSubmessageOrEnum(for token: SwiftProtobuf.SubmessageOrEnumToken) -> SwiftProtobuf.SubmessageOrEnumSchema {
    switch token.index {
    case 1: return .enum(Proto2Unittest_OpenEnumForFlagTest.enumSchema)
    default: preconditionFailure("invalid submessage/enum token; this is a generator bug")
    }
  }

  func _protobuf_messageStorage(accessToken: SwiftProtobuf.MessageStorageToken) -> Swift.AnyObject { _storage }

}

nonisolated extension Proto2Unittest_MessageWithConflictingFlagPrefixes: SwiftProtobuf.GeneratedMessage {
  private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\u{10}\0\0\u{3}\0\0\0\0\0\u{3}\0\0\u{4}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\u{1}\0\0\0\0\u{4}\0\0\0\0\0\0\u{5}\u{2}\0\0\0\0\u{8}\0\0\u{1}\0\0\0\u{5}\u{3}\0\0\0\0\u{c}\0\0\u{2}\0\0\0\u{5}2\0proto2_unittest.MessageWithConflictingFlagPrefixes"
  private static let _protobuf_reflectionData: Swift.StaticString = "d\0\0\0\u{10}?&Ti\u{6}*X$\u{1b}\u{1c}\u{11}|xa\u{15}X\",Sb6\tx;\u{15}\u{17}\u{5}a0;>%\u{1c}3D .y.T\t!%i$qp\u{7}Q\u{5}FI\u{1c}mpF)N'T\0\0"

  static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.MessageWitnesses<Self>.perform)

  func _protobuf_messageStorage(accessToken: SwiftProtobuf.MessageStorageToken) -> Swift.AnyObject { _storage }

}
