// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/protobuf/test_protos/repeated_field_proxy_import_message.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

@_spi(ForGeneratedCodeOnly) import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Proto2Unittest_RepeatedFieldProxyTestImportEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Swift.Int
  case unknown // = 0
  case repeatedFieldProxyTestImportFoo // = 1
  case repeatedFieldProxyTestImportBar // = 2
  case repeatedFieldProxyTestImportBaz // = 3
  case UNRECOGNIZED(Swift.Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Swift.Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .repeatedFieldProxyTestImportFoo
    case 2: self = .repeatedFieldProxyTestImportBar
    case 3: self = .repeatedFieldProxyTestImportBaz
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Swift.Int {
    switch self {
    case .unknown: return 0
    case .repeatedFieldProxyTestImportFoo: return 1
    case .repeatedFieldProxyTestImportBar: return 2
    case .repeatedFieldProxyTestImportBaz: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Proto2Unittest_RepeatedFieldProxyTestImportEnum] = [
    .unknown,
    .repeatedFieldProxyTestImportFoo,
    .repeatedFieldProxyTestImportBar,
    .repeatedFieldProxyTestImportBaz,
  ]

}

struct Proto2Unittest_RepeatedFieldProxyTestImportMessage: @unchecked Swift.Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: Int32 {
    get { _storage.value(at: 4, default: 0, hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(at: 4, to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `value` has been explicitly set.
  var hasValue: Swift.Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  mutating func clearValue() { _uniqueStorage().clearValue(at: 4, type: Int32.self, hasBit: (0, 1)) }

  init() { self._storage = SwiftProtobuf.MessageStorage(schema: Self.messageSchema) }

  private var _storage: SwiftProtobuf.MessageStorage
  private mutating func _uniqueStorage() -> SwiftProtobuf.MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf.MessageStorageToken) { _ = _uniqueStorage() }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto2_unittest"

extension Proto2Unittest_RepeatedFieldProxyTestImportEnum {
  private static let _protobuf_enumSchemaString: Swift.StaticString = "\0\u{4}\0\0\0\00\0proto2_unittest.RepeatedFieldProxyTestImportEnum"
  private static let _protobuf_reflectionData: Swift.StaticString = "p\u{1}\0\00?0\u{5}]1\t\u{e}S\u{1b}*>\u{18}<yP\u{13}/L$7\u{e}SAn!bIxtf]\u{5}j\u{c}@Wd%~O\u{7f}970,eD357+^\0\u{e}<DS\u{14}\u{6}tWKm1\u{19}g x&\u{7}TV\0:\u{7}\ndbq\u{1}-$o\n ZZF7\u{13}\u{1f}\u{15}[ \0])3NO\t71\u{3}I\u{1f}"
  static let enumSchema = SwiftProtobuf.EnumSchema(schema: _protobuf_enumSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.EnumWitnesses<Self>.perform)
}

extension Proto2Unittest_RepeatedFieldProxyTestImportMessage: SwiftProtobuf.GeneratedMessage {
  #if _pointerBitWidth(_64)
    private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\u{8}\0\0\u{1}\0\0\0\0\0\u{1}\0\0\u{2}\0\0\u{8}\0\0\u{1}\0\0\0\0\u{4}\0\0\0\0\0\0\u{5}3\0proto2_unittest.RepeatedFieldProxyTestImportMessage"
  #elseif _pointerBitWidth(_32)
    private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\u{8}\0\0\u{1}\0\0\0\0\0\u{1}\0\0\u{2}\0\0\u{8}\0\0\u{1}\0\0\0\0\u{4}\0\0\0\0\0\0\u{5}3\0proto2_unittest.RepeatedFieldProxyTestImportMessage"
  #else
    #error("Unsupported platform")
  #endif
  private static let _protobuf_reflectionData: Swift.StaticString = "(\0\0\0\0?k,%\u{7}&p\u{1d}-`\u{15}Wp\u{7}u\u{1e}\u{11}fq.r\u{3}~;T\u{8}\0"

  static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.MessageWitnesses<Self>.perform)

  func _protobuf_messageStorage(accessToken: SwiftProtobuf.MessageStorageToken) -> Swift.AnyObject { _storage }

}
