// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/protobuf/unittest_lazy_dependencies.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Protocol Buffers - Google's data interchange format
// Copyright 2008 Google Inc.  All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd

// Author: trafacz@google.com (Todd Rafacz)
//  Based on original Protocol Buffers design by
//  Sanjay Ghemawat, Jeff Dean, and others.
//
// A proto file we will use for unit testing.

@_spi(ForGeneratedCodeOnly) import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Proto2Unittest_LazyImports_ImportedMessage: @unchecked Swift.Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var lazyMessage: Proto2Unittest_LazyImports_LazyMessage {
    get { _storage.value(atIndex: 0, default: Proto2Unittest_LazyImports_LazyMessage(), hasBit: (0, 1)) }
    set { _uniqueStorage().updateValue(atIndex: 0, to: newValue, willBeSet: true, hasBit: (0, 1)) }
  }
  /// Returns true if `lazyMessage` has been explicitly set.
  var hasLazyMessage: Swift.Bool { _storage.isPresent(hasBit: (0, 1)) }
  /// Clears the value of `lazyMessage`. Subsequent reads from it will return its default value.
  mutating func clearLazyMessage() { _uniqueStorage().clearValue(atIndex: 0, type: Proto2Unittest_LazyImports_LazyMessage.self, hasBit: (0, 1)) }

  init() { self._storage = SwiftProtobuf.MessageStorage(schema: Self.messageSchema) }

  private var _storage: SwiftProtobuf.MessageStorage
  private mutating func _uniqueStorage() -> SwiftProtobuf.MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf.MessageStorageToken) { _ = _uniqueStorage() }
}

struct Proto2Unittest_LazyImports_MessageCustomOption: @unchecked Swift.Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  init() { self._storage = SwiftProtobuf.MessageStorage(schema: Self.messageSchema) }

  private var _storage: SwiftProtobuf.MessageStorage
  private mutating func _uniqueStorage() -> SwiftProtobuf.MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf.MessageStorageToken) { _ = _uniqueStorage() }
}

struct Proto2Unittest_LazyImports_MessageCustomOption2: @unchecked Swift.Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  init() { self._storage = SwiftProtobuf.MessageStorage(schema: Self.messageSchema) }

  private var _storage: SwiftProtobuf.MessageStorage
  private mutating func _uniqueStorage() -> SwiftProtobuf.MessageStorage {
    if !isKnownUniquelyReferenced(&_storage) { _storage = _storage.copy() }
    return _storage
  }
  mutating func _protobuf_ensureUniqueStorage(accessToken: SwiftProtobuf.MessageStorageToken) { _ = _uniqueStorage() }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Proto2Unittest_LazyImports_ImportedMessage: SwiftProtobuf.GeneratedMessage {
  private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\u{1}\0\0\u{1}\0\0\0\0\0\u{1}\0\0\u{2}\0\0\0\0\0\0\0\0\u{1}\0\0\0\0\0\0\0\0\u{1}\0\0\0\0\0\00\0\0\u{1}\0\u{b},\0proto2_unittest.lazy_imports.ImportedMessage"
  private static let _protobuf_reflectionData: Swift.StaticString = "D\0\0\0\u{10}\u{7f}FH\u{1}[C#\u{4}\u{15}\\2[\\\u{1f}6\u{18}k>\u{15}\u{12}o]^ \u{18}+\u{1d}&\u{6}0{,#ZQ#\u{14}wF\u{3}$!x\0\0"

  static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.MessageWitnesses<Self>.perform, submessageOrEnumResolver: _protobuf_resolveSubmessageOrEnum)

  private static func _protobuf_resolveSubmessageOrEnum(for token: SwiftProtobuf.SubmessageOrEnumToken) -> SwiftProtobuf.SubmessageOrEnumSchema {
    switch token.index {
    case 1: return .message(Proto2Unittest_LazyImports_LazyMessage.messageSchema)
    default: preconditionFailure("invalid submessage/enum token; this is a generator bug")
    }
  }

  func _protobuf_messageStorage(accessToken: SwiftProtobuf.MessageStorageToken) -> Swift.AnyObject { _storage }

}

extension Proto2Unittest_LazyImports_MessageCustomOption: SwiftProtobuf.GeneratedMessage {
  private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\0\0\0\0\0\0\0\0\0\0\0\0\u{1}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\00\0proto2_unittest.lazy_imports.MessageCustomOption"
  private static let _protobuf_reflectionData: Swift.StaticString = "\u{10}\0\0\0\0_Si=ArYy^\u{15}d\0\0\0"

  static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.MessageWitnesses<Self>.perform)

  func _protobuf_messageStorage(accessToken: SwiftProtobuf.MessageStorageToken) -> Swift.AnyObject { _storage }

}

extension Proto2Unittest_LazyImports_MessageCustomOption2: SwiftProtobuf.GeneratedMessage {
  private static let _protobuf_messageSchemaString: Swift.StaticString = "\0\0\0\0\0\0\0\0\0\0\0\0\0\u{1}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\01\0proto2_unittest.lazy_imports.MessageCustomOption2"
  private static let _protobuf_reflectionData: Swift.StaticString = "\u{10}\0\0\0\0_Si=ArYy^\u{15}d\0\0\0"

  static let messageSchema = SwiftProtobuf.MessageSchema(schema: _protobuf_messageSchemaString, reflection: _protobuf_reflectionData, invokeWitness: SwiftProtobuf.MessageWitnesses<Self>.perform)

  func _protobuf_messageStorage(accessToken: SwiftProtobuf.MessageStorageToken) -> Swift.AnyObject { _storage }

}
