// See Makefile for the logic that generates this
// Protoc errors imply this file is being generated incorrectly
// Swift compile errors are probably bugs in protoc-gen-swift
syntax = "proto3";
package swift_proto_testing.generated;
enum GeneratedSwiftReservedEnum {
  NONE = 0;
  accessToken = 1;
  addPath = 2;
  adjusted = 3;
  advance = 4;
  aggregateValue = 5;
  allCases = 6;
  allowAlias = 7;
  allowPartial = 8;
  allowSurrogates = 9;
  allowURLCharacters = 10;
  allSubmessagesAreInitialized = 11;
  alwaysPrintEnumsAsInts = 12;
  alwaysPrintInt64sAsNumbers = 13;
  annotation = 14;
  any = 15;
  AnyObject = 16;
  anyOf = 17;
  anyTypeURL = 18;
  AnyUnpackError = 19;
  anyValue = 20;
  append = 21;
  appendEnumValue = 22;
  appendInterpolation = 23;
  appendUIntHex = 24;
  appendUnknown = 25;
  appendValue = 26;
  areAllInitialized = 27;
  Array = 28;
  arrayLiteral = 29;
  arraySeparator = 30;
  as = 31;
  asciiValue = 32;
  asQuotedString = 33;
  assertValidAlignment = 34;
  assumedPresentValue = 35;
  async = 36;
  AsyncIterator = 37;
  AsyncIteratorProtocol = 38;
  AsyncMessageSequence = 39;
  at = 40;
  atByteOffset = 41;
  atIndex = 42;
  attr = 43;
  available = 44;
  Base = 45;
  baseAddress = 46;
  begin = 47;
  BinaryDecoding = 48;
  BinaryDecodingError = 49;
  BinaryDecodingOptions = 50;
  BinaryDelimited = 51;
  BinaryEncoder = 52;
  BinaryEncodingError = 53;
  BinaryEncodingOptions = 54;
  binaryProtobufDelimitedMessages = 55;
  BinaryStreamDecoding = 56;
  binaryStreamDecodingError = 57;
  Bit7Reader = 58;
  bitCount = 59;
  bitMask = 60;
  bitPattern = 61;
  BitwiseCopyable = 62;
  body = 63;
  Bool = 64;
  booleanLiteral = 65;
  BooleanLiteralType = 66;
  boolValue = 67;
  boolValueValue = 68;
  borrowing = 69;
  buffer = 70;
  byParsingJSONFrom = 71;
  byParsingTextFormatFrom = 72;
  byte = 73;
  byteOffset = 74;
  bytes = 75;
  bytesInGroup = 76;
  bytesNeeded = 77;
  bytesRead = 78;
  bytesValue = 79;
  bytesValueValue = 80;
  C = 81;
  callAsFunction = 82;
  canonical = 83;
  cardinality = 84;
  CaseIterable = 85;
  ccEnableArenas = 86;
  ccGenericServices = 87;
  CChar = 88;
  changed = 89;
  Character = 90;
  chars = 91;
  chunk = 92;
  class = 93;
  clearAggregateValue = 94;
  clearAllowAlias = 95;
  clearBegin = 96;
  clearCcEnableArenas = 97;
  clearCcGenericServices = 98;
  clearClientStreaming = 99;
  clearCsharpNamespace = 100;
  clearCtype = 101;
  clearDebugRedact = 102;
  clearDefaultSymbolVisibility = 103;
  clearDefaultValue = 104;
  clearDeprecated = 105;
  clearDeprecatedLegacyJsonFieldConflicts = 106;
  clearDeprecationWarning = 107;
  clearDoubleValue = 108;
  clearEdition = 109;
  clearEditionDeprecated = 110;
  clearEditionIntroduced = 111;
  clearEditionRemoved = 112;
  clearEnd = 113;
  clearEnforceNamingStyle = 114;
  clearEnforceProtoLimits = 115;
  clearEnumType = 116;
  clearExtendee = 117;
  clearFeatures = 118;
  clearFeatureSupport = 119;
  clearFieldPresence = 120;
  clearFixedFeatures = 121;
  clearFullName = 122;
  clearGoPackage = 123;
  clearIdempotencyLevel = 124;
  clearIdentifierValue = 125;
  clearInputType = 126;
  clearIsExtension = 127;
  clearJavaGenerateEqualsAndHash = 128;
  clearJavaGenericServices = 129;
  clearJavaMultipleFiles = 130;
  clearJavaOuterClassname = 131;
  clearJavaPackage = 132;
  clearJavaStringCheckUtf8 = 133;
  clearJsonFormat = 134;
  clearJsonName = 135;
  clearJstype = 136;
  clearLabel = 137;
  clearLazy = 138;
  clearLeadingComments = 139;
  clearMapEntry = 140;
  clearMaximumEdition = 141;
  clearMessageEncoding = 142;
  clearMessageSetWireFormat = 143;
  clearMinimumEdition = 144;
  clearName = 145;
  clearNamePart = 146;
  clearNegativeIntValue = 147;
  clearNoStandardDescriptorAccessor = 148;
  clearNumber = 149;
  clearObjcClassPrefix = 150;
  clearOneofIndex = 151;
  clearOptimizeFor = 152;
  clearOptions = 153;
  clearOutputType = 154;
  clearOverridableFeatures = 155;
  clearPackage = 156;
  clearPacked = 157;
  clearPhpClassPrefix = 158;
  clearPhpMetadataNamespace = 159;
  clearPhpNamespace = 160;
  clearPopulatedOneofMember = 161;
  clearPositiveIntValue = 162;
  clearProto3Optional = 163;
  clearPyGenericServices = 164;
  clearRemovalError = 165;
  clearRepeated = 166;
  clearRepeatedFieldEncoding = 167;
  clearRepeatedOrMapField = 168;
  clearReserved = 169;
  clearRetention = 170;
  clearRubyPackage = 171;
  clearSemantic = 172;
  clearServerStreaming = 173;
  clearSingularMessageField = 174;
  clearSourceCodeInfo = 175;
  clearSourceContext = 176;
  clearSourceFile = 177;
  clearStart = 178;
  clearStringValue = 179;
  clearSwiftPrefix = 180;
  clearSyntax = 181;
  clearTrailingComments = 182;
  clearType = 183;
  clearTypeName = 184;
  clearUnverifiedLazy = 185;
  clearUtf8Validation = 186;
  clearValue = 187;
  clearVerification = 188;
  clearVisibility = 189;
  clearWeak = 190;
  clientStreaming = 191;
  Code = 192;
  codeUnits = 193;
  Collection = 194;
  complete = 195;
  compressed = 196;
  computedSize = 197;
  consume = 198;
  consumeAnyTypeURLOrExtensionName = 199;
  consumeArray = 200;
  consumeBool = 201;
  consumeBytes = 202;
  consumedBytes = 203;
  consumeDouble = 204;
  consumeEnumValue = 205;
  consumeFieldOrExtension = 206;
  consumeFieldOrExtensionIfPresent = 207;
  consumeFieldSeparatorIfPresent = 208;
  consumeFloat = 209;
  consumeIdentifier = 210;
  consumeIfPresent = 211;
  consumeLineComment = 212;
  consumeNullIfPresent = 213;
  consumeObject = 214;
  consumePossibleArray = 215;
  consumePrefix = 216;
  consumeSignedInteger = 217;
  consumeString = 218;
  consumeUnsignedDecimalAsDouble = 219;
  consumeUnsignedInteger = 220;
  contains = 221;
  contentsOf = 222;
  ContiguousBytes = 223;
  copy = 224;
  count = 225;
  countVarintsInBuffer = 226;
  create = 227;
  csharpNamespace = 228;
  ctype = 229;
  cumulative = 230;
  cumulativeFrequency = 231;
  current = 232;
  currentOffset = 233;
  currentSchema = 234;
  currentSum = 235;
  CustomDebugStringConvertible = 236;
  CustomStringConvertible = 237;
  data = 238;
  date = 239;
  daySec = 240;
  daysSinceEpoch = 241;
  debugDescription = 242;
  debugRedact = 243;
  declaration = 244;
  decode = 245;
  decodeNextExtension = 246;
  decodingOptions = 247;
  decompress = 248;
  decrementRecursionBudget = 249;
  default = 250;
  defaultAnyTypeURLPrefix = 251;
  defaults = 252;
  defaultSymbolVisibility = 253;
  defaultValue = 254;
  deinitializeField = 255;
  deinitializeFieldForced = 256;
  delimiter = 257;
  denseBelow = 258;
  dependency = 259;
  deprecated = 260;
  deprecatedLegacyJsonFieldConflicts = 261;
  deprecationWarning = 262;
  description = 263;
  destroy = 264;
  dictionaryLiteral = 265;
  digit0 = 266;
  digit1 = 267;
  digitCount = 268;
  digits = 269;
  digitValue = 270;
  discardableResult = 271;
  discardUnknownFields = 272;
  Double = 273;
  doubleValue = 274;
  doubleValueValue = 275;
  duration = 276;
  durationNanos = 277;
  durationSeconds = 278;
  E = 279;
  edition = 280;
  EditionDefault = 281;
  editionDefaults = 282;
  editionDeprecated = 283;
  editionIntroduced = 284;
  editionRemoved = 285;
  Element = 286;
  elementCount = 287;
  elements = 288;
  elementsBuffer = 289;
  elementsReader = 290;
  emitExtensionFieldName = 291;
  emitFieldName = 292;
  emitFieldNumber = 293;
  emitRepeatedField = 294;
  emitValue = 295;
  emptyAnyTypeURL = 296;
  encodeAsBytes = 297;
  encodedSize = 298;
  encoder = 299;
  end = 300;
  endArray = 301;
  endMessageField = 302;
  endRegularField = 303;
  enforceNamingStyle = 304;
  enforceProtoLimits = 305;
  enum = 306;
  enumCase = 307;
  enumName = 308;
  EnumReservedRange = 309;
  enumSchema = 310;
  enumType = 311;
  enumvalue = 312;
  EnumWitnesses = 313;
  EnumWitnessOperation = 314;
  equalSoFar = 315;
  equalToSameFieldIn = 316;
  Equatable = 317;
  Error = 318;
  errorCode = 319;
  errorDescription = 320;
  escapeCode = 321;
  escapeModel = 322;
  escaping = 323;
  exactString = 324;
  expected = 325;
  explicitPresenceCount = 326;
  ExpressibleByArrayLiteral = 327;
  ext = 328;
  extendedGraphemeClusterLiteral = 329;
  ExtendedGraphemeClusterLiteralType = 330;
  extendedMessage = 331;
  ExtendedMessageResolver = 332;
  extendee = 333;
  extensibilityMode = 334;
  extensible = 335;
  extension = 336;
  ExtensionMap = 337;
  extensionRange = 338;
  extensions = 339;
  ExtensionSchema = 340;
  ExtensionStorage = 341;
  ExtensionValueStorage = 342;
  false = 343;
  features = 344;
  FeatureSetEditionDefault = 345;
  featureSupport = 346;
  field = 347;
  fieldCount = 348;
  fieldHasPresence = 349;
  fieldMask = 350;
  FieldMaskError = 351;
  fieldMaskPaths = 352;
  fieldMode = 353;
  fieldName = 354;
  fieldNameCount = 355;
  fieldNumber = 356;
  FieldOrExtensionSchema = 357;
  fieldPresence = 358;
  fields = 359;
  fieldSchemaSize = 360;
  fieldSize = 361;
  FieldTag = 362;
  file = 363;
  fileName = 364;
  final = 365;
  firstItem = 366;
  firstNontrivialOffset = 367;
  fixed2ByteBase128 = 368;
  fixed32 = 369;
  fixed3ByteBase128 = 370;
  fixed64 = 371;
  fixedFeatures = 372;
  Float = 373;
  floatLiteral = 374;
  FloatLiteralType = 375;
  floatValue = 376;
  floatValueValue = 377;
  for = 378;
  forAssumedPresentRepeatedEnumField = 379;
  forAssumedPresentRepeatedMessageField = 380;
  forAssumedPresentSingularMessageField = 381;
  forCumulativeFrequency = 382;
  forEachMapEntry = 383;
  forEachMessage = 384;
  forEachRawValue = 385;
  forEnumCase = 386;
  forFieldNumber = 387;
  ForGeneratedCodeOnly = 388;
  forJSONName = 389;
  forLazyMapEntry = 390;
  forMapEntry = 391;
  formatDuration = 392;
  formatTimestamp = 393;
  forMessageName = 394;
  formUnion = 395;
  forNewlyAppendedElementOfRepeatedMessageField = 396;
  forSingularMessageField = 397;
  forTextName = 398;
  forTypeURL = 399;
  ForwardParser = 400;
  forWritingInto = 401;
  fractionalDigits = 402;
  frequencies = 403;
  frequency = 404;
  FrequencyModel = 405;
  frequencyRange = 406;
  from = 407;
  fromAscii2 = 408;
  fromAscii4 = 409;
  fromByteOffset = 410;
  fullName = 411;
  func = 412;
  function = 413;
  GeneratedMessage = 414;
  get = 415;
  Google_Protobuf_Any = 416;
  Google_Protobuf_Api = 417;
  Google_Protobuf_BoolValue = 418;
  Google_Protobuf_BytesValue = 419;
  Google_Protobuf_DescriptorProto = 420;
  Google_Protobuf_DoubleValue = 421;
  Google_Protobuf_Duration = 422;
  Google_Protobuf_Edition = 423;
  Google_Protobuf_Empty = 424;
  Google_Protobuf_Enum = 425;
  Google_Protobuf_EnumDescriptorProto = 426;
  Google_Protobuf_EnumOptions = 427;
  Google_Protobuf_EnumValue = 428;
  Google_Protobuf_EnumValueDescriptorProto = 429;
  Google_Protobuf_EnumValueOptions = 430;
  Google_Protobuf_ExtensionRangeOptions = 431;
  Google_Protobuf_FeatureSet = 432;
  Google_Protobuf_FeatureSetDefaults = 433;
  Google_Protobuf_Field = 434;
  Google_Protobuf_FieldDescriptorProto = 435;
  Google_Protobuf_FieldMask = 436;
  Google_Protobuf_FieldOptions = 437;
  Google_Protobuf_FileDescriptorProto = 438;
  Google_Protobuf_FileDescriptorSet = 439;
  Google_Protobuf_FileOptions = 440;
  Google_Protobuf_FloatValue = 441;
  Google_Protobuf_GeneratedCodeInfo = 442;
  Google_Protobuf_Int32Value = 443;
  Google_Protobuf_Int64Value = 444;
  Google_Protobuf_ListValue = 445;
  Google_Protobuf_MessageOptions = 446;
  Google_Protobuf_Method = 447;
  Google_Protobuf_MethodDescriptorProto = 448;
  Google_Protobuf_MethodOptions = 449;
  Google_Protobuf_Mixin = 450;
  Google_Protobuf_NullValue = 451;
  Google_Protobuf_OneofDescriptorProto = 452;
  Google_Protobuf_OneofOptions = 453;
  Google_Protobuf_Option = 454;
  Google_Protobuf_ServiceDescriptorProto = 455;
  Google_Protobuf_ServiceOptions = 456;
  Google_Protobuf_SourceCodeInfo = 457;
  Google_Protobuf_SourceContext = 458;
  Google_Protobuf_StringValue = 459;
  Google_Protobuf_Struct = 460;
  Google_Protobuf_SymbolVisibility = 461;
  Google_Protobuf_Syntax = 462;
  Google_Protobuf_Timestamp = 463;
  Google_Protobuf_Type = 464;
  Google_Protobuf_UInt32Value = 465;
  Google_Protobuf_UInt64Value = 466;
  Google_Protobuf_UninterpretedOption = 467;
  Google_Protobuf_Value = 468;
  goPackage = 469;
  gotNextElement = 470;
  group = 471;
  groupFieldNumberStack = 472;
  hadFieldsOtherThanValue = 473;
  hasAggregateValue = 474;
  hasAllowAlias = 475;
  hasAvailableData = 476;
  hasBegin = 477;
  HasBit = 478;
  hasCcEnableArenas = 479;
  hasCcGenericServices = 480;
  hasClientStreaming = 481;
  hasCsharpNamespace = 482;
  hasCtype = 483;
  hasDebugRedact = 484;
  hasDefaultSymbolVisibility = 485;
  hasDefaultValue = 486;
  hasDeprecated = 487;
  hasDeprecatedLegacyJsonFieldConflicts = 488;
  hasDeprecationWarning = 489;
  hasDoubleValue = 490;
  hasEdition = 491;
  hasEditionDeprecated = 492;
  hasEditionIntroduced = 493;
  hasEditionRemoved = 494;
  hasEnd = 495;
  hasEnforceNamingStyle = 496;
  hasEnforceProtoLimits = 497;
  hasEnumType = 498;
  hasEscapes = 499;
  hasExtendee = 500;
  hasFeatures = 501;
  hasFeatureSupport = 502;
  hasFieldPresence = 503;
  hasFixedFeatures = 504;
  hasFullName = 505;
  hasGoPackage = 506;
  hash = 507;
  Hashable = 508;
  hasher = 509;
  hasIdempotencyLevel = 510;
  hasIdentifierValue = 511;
  hasInputType = 512;
  hasIsExtension = 513;
  hasJavaGenerateEqualsAndHash = 514;
  hasJavaGenericServices = 515;
  hasJavaMultipleFiles = 516;
  hasJavaOuterClassname = 517;
  hasJavaPackage = 518;
  hasJavaStringCheckUtf8 = 519;
  hasJsonFormat = 520;
  hasJsonName = 521;
  hasJstype = 522;
  hasLabel = 523;
  hasLazy = 524;
  hasLeadingComments = 525;
  hasMapEntry = 526;
  hasMaximumEdition = 527;
  hasMessageEncoding = 528;
  hasMessageSetWireFormat = 529;
  hasMinimumEdition = 530;
  hasName = 531;
  hasNamePart = 532;
  hasNegativeIntValue = 533;
  hasNonEmptyNullRepresentation = 534;
  hasNoStandardDescriptorAccessor = 535;
  hasNumber = 536;
  hasObjcClassPrefix = 537;
  hasOneofIndex = 538;
  hasOptimizeFor = 539;
  hasOptions = 540;
  hasOutputType = 541;
  hasOverridableFeatures = 542;
  hasPackage = 543;
  hasPacked = 544;
  hasPhpClassPrefix = 545;
  hasPhpMetadataNamespace = 546;
  hasPhpNamespace = 547;
  hasPositiveIntValue = 548;
  hasProto3Optional = 549;
  hasPyGenericServices = 550;
  hasRemovalError = 551;
  hasRepeated = 552;
  hasRepeatedFieldEncoding = 553;
  hasReserved = 554;
  hasRetention = 555;
  hasRubyPackage = 556;
  hasSemantic = 557;
  hasServerStreaming = 558;
  hasSourceCodeInfo = 559;
  hasSourceContext = 560;
  hasSourceFile = 561;
  hasStart = 562;
  hasStringValue = 563;
  hasSwiftPrefix = 564;
  hasSyntax = 565;
  hasTrailingComments = 566;
  hasType = 567;
  hasTypeName = 568;
  hasUnverifiedLazy = 569;
  hasUtf8Validation = 570;
  hasValue = 571;
  hasVerification = 572;
  hasVisibility = 573;
  hasWeak = 574;
  high = 575;
  highSurrogate = 576;
  hour = 577;
  i = 578;
  idempotencyLevel = 579;
  identifierValue = 580;
  idx = 581;
  if = 582;
  ignored = 583;
  ignoreUnknownExtensionFields = 584;
  ignoreUnknownFields = 585;
  in = 586;
  inAssumedPresentRepeatedEnumField = 587;
  incrementFrequency = 588;
  incrementRecursionBudget = 589;
  index = 590;
  init = 591;
  inout = 592;
  input = 593;
  inputType = 594;
  insert = 595;
  insertMapEntry = 596;
  Int = 597;
  Int32 = 598;
  int32ValueValue = 599;
  Int64 = 600;
  int64ValueValue = 601;
  integerLiteral = 602;
  IntegerLiteralType = 603;
  integerValue = 604;
  intersect = 605;
  into = 606;
  ints = 607;
  invalidAnyTypeURL = 608;
  invalidValues = 609;
  invokeWitness = 610;
  InvokeWitnessFunction = 611;
  isA = 612;
  isAlphanumeric = 613;
  isDigit = 614;
  isEqual = 615;
  isEqualTo = 616;
  isEscape = 617;
  isExtension = 618;
  isField = 619;
  isFieldNameReserved = 620;
  isFieldNumberReserved = 621;
  isFloat = 622;
  isHexDigit = 623;
  isHexNumber = 624;
  isIdentifier = 625;
  isInitialized = 626;
  isJSONEscape = 627;
  isJSONSymbol = 628;
  isLetter = 629;
  isMapField = 630;
  isMessageInitializedRecursive = 631;
  isMessageInitializedShallow = 632;
  isNameReserved = 633;
  isNegative = 634;
  isNumberReserved = 635;
  isOctalDigit = 636;
  isOctalNumber = 637;
  isPacked = 638;
  isPathValid = 639;
  isPresent = 640;
  isPrintableASCII = 641;
  isShallowInitCheckPassed = 642;
  isTrackingGroup = 643;
  isTypeURLValid = 644;
  isUnprintable = 645;
  isURLCharacter = 646;
  isValid = 647;
  isValidValue = 648;
  isWhitespace = 649;
  iterator = 650;
  iteratorAlignment = 651;
  iteratorSize = 652;
  javaGenerateEqualsAndHash = 653;
  javaGenericServices = 654;
  javaMultipleFiles = 655;
  javaOuterClassname = 656;
  javaPackage = 657;
  javaStringCheckUtf8 = 658;
  json = 659;
  JSONDecoding = 660;
  JSONDecodingError = 661;
  JSONDecodingOptions = 662;
  JSONEncoder = 663;
  JSONEncoding = 664;
  JSONEncodingError = 665;
  JSONEncodingOptions = 666;
  jsonFormat = 667;
  jsonName = 668;
  jsonPath = 669;
  jsonPaths = 670;
  JSONReader = 671;
  jsonString = 672;
  jsonUTF8Bytes = 673;
  jsonUTF8Data = 674;
  jstype = 675;
  K = 676;
  kChunkSize = 677;
  keeping = 678;
  Key = 679;
  keyLessThan = 680;
  kind = 681;
  kinds = 682;
  label = 683;
  lastConsumed = 684;
  lazy = 685;
  leadingComments = 686;
  leadingDetachedComments = 687;
  leadingZeroBitCount = 688;
  length = 689;
  lengthBits = 690;
  lengthModel = 691;
  let = 692;
  lexicographicallyPrecedes = 693;
  lhs = 694;
  lhsIter = 695;
  line = 696;
  listValue = 697;
  listValueValues = 698;
  littleEndian = 699;
  load = 700;
  location = 701;
  lock = 702;
  LockPrimitive = 703;
  low = 704;
  M = 705;
  mainModel = 706;
  mainModelSize = 707;
  major = 708;
  makeAsyncIterator = 709;
  makeError = 710;
  makeIterator = 711;
  malformedLength = 712;
  map = 713;
  mapEntry = 714;
  mapEntryKey = 715;
  mapEntryValue = 716;
  MapEntryWitnesses = 717;
  mapEntryWorkingSpace = 718;
  mask = 719;
  matchCode = 720;
  maximumEdition = 721;
  maxMatchLength = 722;
  mdayStart = 723;
  merge = 724;
  MergeOptions = 725;
  Message = 726;
  messageBytes = 727;
  messageDepthLimit = 728;
  messageEncoding = 729;
  messageName = 730;
  MessageSchema = 731;
  messageSet = 732;
  messageSetItem = 733;
  messageSetItemTagsEncodedSize = 734;
  messageSetMessage = 735;
  messageSetTypeID = 736;
  messageSetWireFormat = 737;
  messageSize = 738;
  messageStorage = 739;
  MessageStorageToken = 740;
  messageType = 741;
  MessageWitnesses = 742;
  MessageWitnessOperation = 743;
  method = 744;
  methods = 745;
  min = 746;
  minimumEdition = 747;
  minMatchLength = 748;
  minor = 749;
  mixins = 750;
  mode = 751;
  month = 752;
  mutating = 753;
  mutex = 754;
  n = 755;
  name = 756;
  named = 757;
  NamePart = 758;
  nanos = 759;
  negative = 760;
  negativeIntValue = 761;
  nestedType = 762;
  newTotal = 763;
  newValue = 764;
  next = 765;
  nextByte = 766;
  nextLengthDelimitedSlice = 767;
  nextLittleEndianUInt32 = 768;
  nextLittleEndianUInt64 = 769;
  nextTag = 770;
  nextVarInt = 771;
  nextVarintAsValidatedDelimitedLength = 772;
  nil = 773;
  nilLiteral = 774;
  noBytesAvailable = 775;
  nonextensible = 776;
  nonisolated = 777;
  noStandardDescriptorAccessor = 778;
  nullValue = 779;
  number = 780;
  numberValue = 781;
  objcClassPrefix = 782;
  of = 783;
  ofBytesFieldAtIndex = 784;
  offset = 785;
  offsetModel = 786;
  offsetOrIndexValue = 787;
  ofMapFieldAtIndex = 788;
  ofMessageFieldAtIndex = 789;
  ofRepeatedFieldAtIndex = 790;
  ofStringFieldAtIndex = 791;
  ofTagWithFieldNumber = 792;
  oneofDecl = 793;
  oneofIndex = 794;
  oneofOffset = 795;
  OneofPresence = 796;
  oneofs = 797;
  OneOf_Kind = 798;
  operation = 799;
  optimizeFor = 800;
  OptimizeMode = 801;
  Optional = 802;
  optionDependency = 803;
  OptionRetention = 804;
  options = 805;
  OptionTargetType = 806;
  other = 807;
  output = 808;
  outputBytes = 809;
  outputType = 810;
  overridableFeatures = 811;
  ownerSchema = 812;
  p = 813;
  package = 814;
  packed = 815;
  packedBucketOffsetsHi = 816;
  packedBucketOffsetsLo = 817;
  packedBucketStrides = 818;
  padding = 819;
  parse = 820;
  parseDuration = 821;
  parseJSONBuffer = 822;
  parseTimestamp = 823;
  parsingError = 824;
  partial = 825;
  path = 826;
  paths = 827;
  perform = 828;
  phpClassPrefix = 829;
  phpMetadataNamespace = 830;
  phpNamespace = 831;
  pointer = 832;
  populatedOneofMember = 833;
  pos = 834;
  positiveIntValue = 835;
  possibleWKTValueJSON = 836;
  prefix = 837;
  presence = 838;
  preserveProtoFieldNames = 839;
  printUnknownFields = 840;
  proto3Optional = 841;
  ProtobufAPIVersionCheck = 842;
  ProtobufAPIVersion_2 = 843;
  protobufBytes = 844;
  protobufData = 845;
  ProtobufMapBoolField = 846;
  ProtobufMapDataField = 847;
  ProtobufMapDoubleField = 848;
  ProtobufMapEnumField = 849;
  ProtobufMapFloatField = 850;
  ProtobufMapInt32Field = 851;
  ProtobufMapInt64Field = 852;
  ProtobufMapKey = 853;
  ProtobufMapKeyKind = 854;
  ProtobufMapMessageField = 855;
  ProtobufMapParticipant = 856;
  ProtobufMapStringField = 857;
  ProtobufMapUInt32Field = 858;
  ProtobufMapUInt64Field = 859;
  protobuf_ensureUniqueStorage = 860;
  protobuf_enumSchemaString = 861;
  protobuf_extensionStorage = 862;
  protobuf_mapWitness = 863;
  protobuf_messageSchemaString = 864;
  protobuf_messageStorage = 865;
  protobuf_reflectionData = 866;
  protobuf_resolveSubmessageOrEnum = 867;
  protobuf_uniqueExtensionStorage = 868;
  protocol = 869;
  ProtoLimitsFeature = 870;
  protoMessageName = 871;
  protoPaths = 872;
  pthread_mutexattr_t = 873;
  public = 874;
  publicDependency = 875;
  putBoolValue = 876;
  putBytesValue = 877;
  putDoubleValue = 878;
  putEnumValue = 879;
  putFixedUInt32 = 880;
  putFixedUInt64 = 881;
  putFloatValue = 882;
  putInt64 = 883;
  putStringValue = 884;
  putUInt64 = 885;
  putUInt64Hex = 886;
  putVarInt = 887;
  putZigZagVarInt = 888;
  pyGenericServices = 889;
  R = 890;
  radix = 891;
  rangeDecoder = 892;
  rawBufferPointer = 893;
  rawChars = 894;
  rawFieldType = 895;
  rawPointer = 896;
  rawPresence = 897;
  RawRepresentable = 898;
  rawValue = 899;
  readBytes = 900;
  reader = 901;
  reason = 902;
  recursionBudget = 903;
  reflection = 904;
  ReflectionTable = 905;
  register = 906;
  release = 907;
  removalError = 908;
  remove = 909;
  repeated = 910;
  repeatedFieldEncoding = 911;
  repeating = 912;
  replaceRepeatedFields = 913;
  reportingURLCharacters = 914;
  requestStreaming = 915;
  requestTypeURL = 916;
  requiredCount = 917;
  requiredSize = 918;
  resolveLazy = 919;
  resolveLazyMapWitness = 920;
  responseStreaming = 921;
  responseTypeURL = 922;
  result = 923;
  retention = 924;
  rethrows = 925;
  revision = 926;
  rhs = 927;
  rhsIter = 928;
  root = 929;
  rubyPackage = 930;
  S = 931;
  sawEndGroup = 932;
  sawSection4Characters = 933;
  sawSection5Characters = 934;
  scalar = 935;
  scalarStride = 936;
  schema = 937;
  seconds = 938;
  seenFields = 939;
  self = 940;
  semantic = 941;
  Sendable = 942;
  Sequence = 943;
  serialize = 944;
  serializeBoolField = 945;
  serializeBytes = 946;
  serializeBytesField = 947;
  serializedBytes = 948;
  serializedBytesSize = 949;
  serializedData = 950;
  serializeDoubleField = 951;
  serializedSize = 952;
  serializeFixed32Field = 953;
  serializeFixed64Field = 954;
  serializeFloatField = 955;
  serializeInt32Field = 956;
  serializeInt64Field = 957;
  serializeJSON = 958;
  serializePackedFixedField = 959;
  serializePackedVarintsField = 960;
  serializeSFixed32Field = 961;
  serializeSFixed64Field = 962;
  serializeSInt32Field = 963;
  serializeSInt64Field = 964;
  serializeStringField = 965;
  serializeText = 966;
  serializeUInt32Field = 967;
  serializeUInt64Field = 968;
  serverStreaming = 969;
  service = 970;
  Set = 971;
  sfixed32 = 972;
  sfixed64 = 973;
  shift = 974;
  sint32 = 975;
  sint64 = 976;
  size = 977;
  skipField = 978;
  skipFieldMessage = 979;
  skipFieldValue = 980;
  slice = 981;
  sliceBySkippingField = 982;
  some = 983;
  source = 984;
  sourceCodeInfo = 985;
  sourceContext = 986;
  sourceEncoding = 987;
  sourceFile = 988;
  SourceLocation = 989;
  span = 990;
  spi = 991;
  split = 992;
  stable = 993;
  start = 994;
  startArray = 995;
  startField = 996;
  startIndex = 997;
  startMessageField = 998;
  startRegularField = 999;
  static = 1000;
  StaticString = 1001;
  storage = 1002;
  storageBucket = 1003;
  String = 1004;
  stringLiteral = 1005;
  StringLiteralType = 1006;
  StringProtocol = 1007;
  stringResult = 1008;
  stringValue = 1009;
  stringValueValue = 1010;
  struct = 1011;
  structFields = 1012;
  structValue = 1013;
  submessageIndex = 1014;
  submessageOrEnumIndex = 1015;
  SubmessageOrEnumResolver = 1016;
  SubmessageOrEnumSchema = 1017;
  SubmessageOrEnumToken = 1018;
  submessageStorage = 1019;
  subOptions = 1020;
  subPaths = 1021;
  subReader = 1022;
  subscript = 1023;
  subtract = 1024;
  success = 1025;
  sum = 1026;
  Swift = 1027;
  swiftPrefix = 1028;
  SwiftProtobuf = 1029;
  SwiftProtobufContiguousBytes = 1030;
  SwiftProtobufError = 1031;
  symbol = 1032;
  symbolName = 1033;
  syntax = 1034;
  T = 1035;
  tag = 1036;
  tagAndSizeData = 1037;
  tagAndSizeSize = 1038;
  target = 1039;
  targets = 1040;
  testReader = 1041;
  text = 1042;
  textFormat = 1043;
  TextFormatDecoding = 1044;
  textFormatDecodingError = 1045;
  TextFormatDecodingOptions = 1046;
  TextFormatEncoder = 1047;
  TextFormatEncodingOptions = 1048;
  textFormatName = 1049;
  TextFormatReader = 1050;
  textFormatString = 1051;
  textName = 1052;
  throws = 1053;
  timeInterval = 1054;
  timeIntervalSince1970 = 1055;
  timeIntervalSinceReferenceDate = 1056;
  timestampNanos = 1057;
  timestampSeconds = 1058;
  to = 1059;
  Token = 1060;
  tokenizer = 1061;
  tokenType = 1062;
  tooLarge = 1063;
  toRepeatedEnumField = 1064;
  total = 1065;
  totalEntriesSize = 1066;
  totalEnumsSize = 1067;
  totalSize = 1068;
  trailingComments = 1069;
  trim = 1070;
  true = 1071;
  try = 1072;
  tryConsumeComment = 1073;
  tryConsumeWhitespace = 1074;
  type = 1075;
  typealias = 1076;
  typedPointer = 1077;
  TypeEnum = 1078;
  typeName = 1079;
  typePrefix = 1080;
  typeStart = 1081;
  typeURL = 1082;
  UInt16 = 1083;
  UInt32 = 1084;
  uint32ValueValue = 1085;
  UInt64 = 1086;
  uint64ValueValue = 1087;
  UInt8 = 1088;
  unchecked = 1089;
  Unicode = 1090;
  unicodeScalarLiteral = 1091;
  UnicodeScalarLiteralType = 1092;
  uninterpretedOption = 1093;
  union = 1094;
  uniqueMessageStorage = 1095;
  uniqueStorage = 1096;
  unknownAnyTypeURL = 1097;
  unknownFields = 1098;
  UnknownStorage = 1099;
  unlock = 1100;
  Unmanaged = 1101;
  UnsafeBufferPointer = 1102;
  UnsafeMutablePointer = 1103;
  unsafeMutablePointerToValue = 1104;
  UnsafeMutableRawBufferPointer = 1105;
  unsafeMutableRawPointer = 1106;
  UnsafeRawBufferPointer = 1107;
  unsafeRawPointer = 1108;
  unverifiedLazy = 1109;
  updatePopulatedOneofMember = 1110;
  updatePresence = 1111;
  updateValue = 1112;
  upperBound = 1113;
  uppercasedAssumingASCII = 1114;
  url = 1115;
  urlCharacters = 1116;
  urlPrefix = 1117;
  usableFromInline = 1118;
  useDeterministicOrdering = 1119;
  utf8 = 1120;
  utf8CodeUnitsEqual = 1121;
  utf8Error = 1122;
  UTF8Name = 1123;
  utf8Validation = 1124;
  v = 1125;
  value = 1126;
  valueBoolValue = 1127;
  valueCount = 1128;
  valueError = 1129;
  valueListValue = 1130;
  valueNullValue = 1131;
  valueNumberValue = 1132;
  values = 1133;
  valueStringValue = 1134;
  valueStructValue = 1135;
  var = 1136;
  verification = 1137;
  VerificationState = 1138;
  verifyNotNull = 1139;
  Version = 1140;
  versionString = 1141;
  visibility = 1142;
  VisibilityFeature = 1143;
  Void = 1144;
  wasEmpty = 1145;
  wasNameAlreadyConsumed = 1146;
  weak = 1147;
  weakDependency = 1148;
  wereNameAndColonAlreadyConsumed = 1149;
  where = 1150;
  willBeSet = 1151;
  windowSize = 1152;
  windowSizeBits = 1153;
  wireFormat = 1154;
  WireFormatReader = 1155;
  with = 1156;
  withLock = 1157;
  withRawValue = 1158;
  withReaderForNextGroup = 1159;
  withReaderForNextLengthDelimitedSlice = 1160;
  withReaderForNextObject = 1161;
  withTable = 1162;
  withUnsafeBytes = 1163;
  withUnsafeMutableBytes = 1164;
  witness = 1165;
  workingSpace = 1166;
  Wrapped = 1167;
  wrappedValue = 1168;
  written = 1169;
  yday = 1170;
  zeroOut = 1171;
}
