// See Makefile for the logic that generates this
// Protoc errors imply this file is being generated incorrectly
// Swift compile errors are probably bugs in protoc-gen-swift
syntax = "proto3";
package swift_proto_testing.generated;
enum GeneratedSwiftReservedEnum {
  NONE = 0;
  accessToken = 1;
  addPath = 2;
  adjusted = 3;
  advance = 4;
  aggregateValue = 5;
  allCases = 6;
  allowAlias = 7;
  allowPartial = 8;
  allowSurrogates = 9;
  allowURLCharacters = 10;
  allSubmessagesAreInitialized = 11;
  alwaysPrintEnumsAsInts = 12;
  alwaysPrintInt64sAsNumbers = 13;
  annotation = 14;
  any = 15;
  AnyObject = 16;
  anyOf = 17;
  anyTypeURL = 18;
  AnyUnpackError = 19;
  anyValue = 20;
  append = 21;
  appendEnumValue = 22;
  appendInterpolation = 23;
  appendUIntHex = 24;
  appendUnknown = 25;
  appendValue = 26;
  areAllInitialized = 27;
  areEqual = 28;
  Array = 29;
  arrayLiteral = 30;
  arraySeparator = 31;
  as = 32;
  asciiValue = 33;
  asQuotedString = 34;
  assertValidAlignment = 35;
  assumedPresentValue = 36;
  async = 37;
  AsyncIterator = 38;
  AsyncIteratorProtocol = 39;
  AsyncMessageSequence = 40;
  at = 41;
  atByteOffset = 42;
  atIndex = 43;
  attr = 44;
  available = 45;
  Base = 46;
  baseAddress = 47;
  begin = 48;
  BinaryDecoding = 49;
  BinaryDecodingError = 50;
  BinaryDecodingOptions = 51;
  BinaryDelimited = 52;
  BinaryEncoder = 53;
  BinaryEncodingError = 54;
  BinaryEncodingOptions = 55;
  binaryProtobufDelimitedMessages = 56;
  BinaryStreamDecoding = 57;
  binaryStreamDecodingError = 58;
  Bit7Reader = 59;
  bitCount = 60;
  bitMask = 61;
  bitPattern = 62;
  BitwiseCopyable = 63;
  body = 64;
  Bool = 65;
  booleanLiteral = 66;
  BooleanLiteralType = 67;
  boolValue = 68;
  boolValueValue = 69;
  borrowing = 70;
  buffer = 71;
  byParsingJSONFrom = 72;
  byParsingTextFormatFrom = 73;
  byte = 74;
  byteOffset = 75;
  bytes = 76;
  bytesInGroup = 77;
  bytesNeeded = 78;
  bytesRead = 79;
  bytesValue = 80;
  bytesValueValue = 81;
  C = 82;
  callAsFunction = 83;
  canonical = 84;
  cardinality = 85;
  CaseIterable = 86;
  ccEnableArenas = 87;
  ccGenericServices = 88;
  CChar = 89;
  changed = 90;
  Character = 91;
  chars = 92;
  chunk = 93;
  class = 94;
  clearAggregateValue = 95;
  clearAllowAlias = 96;
  clearBegin = 97;
  clearCcEnableArenas = 98;
  clearCcGenericServices = 99;
  clearClientStreaming = 100;
  clearCsharpNamespace = 101;
  clearCtype = 102;
  clearDebugRedact = 103;
  clearDefaultSymbolVisibility = 104;
  clearDefaultValue = 105;
  clearDeprecated = 106;
  clearDeprecatedLegacyJsonFieldConflicts = 107;
  clearDeprecationWarning = 108;
  clearDoubleValue = 109;
  clearEdition = 110;
  clearEditionDeprecated = 111;
  clearEditionIntroduced = 112;
  clearEditionRemoved = 113;
  clearEnd = 114;
  clearEnforceNamingStyle = 115;
  clearEnforceProtoLimits = 116;
  clearEnumType = 117;
  clearEnumValue = 118;
  clearExtendee = 119;
  clearFeatures = 120;
  clearFeatureSupport = 121;
  clearFieldPresence = 122;
  clearFixedFeatures = 123;
  clearFullName = 124;
  clearGoPackage = 125;
  clearIdempotencyLevel = 126;
  clearIdentifierValue = 127;
  clearInputType = 128;
  clearIsExtension = 129;
  clearJavaGenerateEqualsAndHash = 130;
  clearJavaGenericServices = 131;
  clearJavaMultipleFiles = 132;
  clearJavaOuterClassname = 133;
  clearJavaPackage = 134;
  clearJavaStringCheckUtf8 = 135;
  clearJsonFormat = 136;
  clearJsonName = 137;
  clearJstype = 138;
  clearLabel = 139;
  clearLazy = 140;
  clearLeadingComments = 141;
  clearMapEntry = 142;
  clearMaximumEdition = 143;
  clearMessageEncoding = 144;
  clearMessageSetWireFormat = 145;
  clearMessageValue = 146;
  clearMinimumEdition = 147;
  clearName = 148;
  clearNamePart = 149;
  clearNegativeIntValue = 150;
  clearNoStandardDescriptorAccessor = 151;
  clearNumber = 152;
  clearObjcClassPrefix = 153;
  clearOneofIndex = 154;
  clearOptimizeFor = 155;
  clearOptions = 156;
  clearOutputType = 157;
  clearOverridableFeatures = 158;
  clearPackage = 159;
  clearPacked = 160;
  clearPhpClassPrefix = 161;
  clearPhpMetadataNamespace = 162;
  clearPhpNamespace = 163;
  clearPopulatedOneofMember = 164;
  clearPositiveIntValue = 165;
  clearProto3Optional = 166;
  clearPyGenericServices = 167;
  clearRemovalError = 168;
  clearRepeated = 169;
  clearRepeatedFieldEncoding = 170;
  clearRepeatedOrMapField = 171;
  clearReserved = 172;
  clearRetention = 173;
  clearRubyPackage = 174;
  clearSemantic = 175;
  clearServerStreaming = 176;
  clearSingularMessageField = 177;
  clearSourceCodeInfo = 178;
  clearSourceContext = 179;
  clearSourceFile = 180;
  clearStart = 181;
  clearStringValue = 182;
  clearSwiftPrefix = 183;
  clearSyntax = 184;
  clearTrailingComments = 185;
  clearType = 186;
  clearTypeName = 187;
  clearUnverifiedLazy = 188;
  clearUtf8Validation = 189;
  clearValue = 190;
  clearVerification = 191;
  clearVisibility = 192;
  clearWeak = 193;
  clientStreaming = 194;
  Code = 195;
  codeUnits = 196;
  Collection = 197;
  complete = 198;
  compressed = 199;
  computedSize = 200;
  consume = 201;
  consumeAnyTypeURLOrExtensionName = 202;
  consumeArray = 203;
  consumeBool = 204;
  consumeBytes = 205;
  consumedBytes = 206;
  consumeDouble = 207;
  consumeEnumValue = 208;
  consumeFieldOrExtension = 209;
  consumeFieldOrExtensionIfPresent = 210;
  consumeFieldSeparatorIfPresent = 211;
  consumeFloat = 212;
  consumeIdentifier = 213;
  consumeIfPresent = 214;
  consumeLineComment = 215;
  consumeNullIfPresent = 216;
  consumeObject = 217;
  consumePossibleArray = 218;
  consumePrefix = 219;
  consumeSignedInteger = 220;
  consumeString = 221;
  consumeUnsignedDecimalAsDouble = 222;
  consumeUnsignedInteger = 223;
  contains = 224;
  contentsOf = 225;
  ContiguousBytes = 226;
  convention = 227;
  copy = 228;
  count = 229;
  countVarintsInBuffer = 230;
  create = 231;
  csharpNamespace = 232;
  ctype = 233;
  cumulative = 234;
  cumulativeFrequency = 235;
  current = 236;
  currentOffset = 237;
  currentSchema = 238;
  currentSum = 239;
  CustomDebugStringConvertible = 240;
  CustomStringConvertible = 241;
  data = 242;
  date = 243;
  daySec = 244;
  daysSinceEpoch = 245;
  debugDescription = 246;
  debugRedact = 247;
  declaration = 248;
  decode = 249;
  decodeNextExtension = 250;
  decodingOptions = 251;
  decompress = 252;
  decrementRecursionBudget = 253;
  default = 254;
  defaultAnyTypeURLPrefix = 255;
  defaults = 256;
  defaultSymbolVisibility = 257;
  defaultValue = 258;
  deinitializeField = 259;
  deinitializeFieldForced = 260;
  deinitializeSubmessage = 261;
  delimiter = 262;
  denseBelow = 263;
  dependency = 264;
  deprecated = 265;
  deprecatedLegacyJsonFieldConflicts = 266;
  deprecationWarning = 267;
  description = 268;
  destroy = 269;
  dictionaryLiteral = 270;
  digit0 = 271;
  digit1 = 272;
  digitCount = 273;
  digits = 274;
  digitValue = 275;
  discardableResult = 276;
  discardUnknownFields = 277;
  Double = 278;
  doubleValue = 279;
  doubleValueValue = 280;
  duration = 281;
  durationNanos = 282;
  durationSeconds = 283;
  DynamicLookupThunk = 284;
  DynamicMapWitnessThunk = 285;
  E = 286;
  edition = 287;
  EditionDefault = 288;
  editionDefaults = 289;
  editionDeprecated = 290;
  editionIntroduced = 291;
  editionRemoved = 292;
  Element = 293;
  elementCount = 294;
  elements = 295;
  elementsBuffer = 296;
  elementsReader = 297;
  emitExtensionFieldName = 298;
  emitFieldName = 299;
  emitFieldNumber = 300;
  emitRepeatedField = 301;
  emitValue = 302;
  emptyAnyTypeURL = 303;
  encodeAsBytes = 304;
  encodedSize = 305;
  encoder = 306;
  end = 307;
  endArray = 308;
  endMessageField = 309;
  endRegularField = 310;
  enforceNamingStyle = 311;
  enforceProtoLimits = 312;
  enum = 313;
  enumCase = 314;
  enumName = 315;
  EnumReservedRange = 316;
  enumSchema = 317;
  enumType = 318;
  enumValue = 319;
  EnumWitnesses = 320;
  EnumWitnessOperation = 321;
  equalSoFar = 322;
  equalToSameFieldIn = 323;
  Equatable = 324;
  Error = 325;
  errorCode = 326;
  errorDescription = 327;
  escapeCode = 328;
  escapeModel = 329;
  escaping = 330;
  exactString = 331;
  expected = 332;
  explicitPresenceCount = 333;
  ExpressibleByArrayLiteral = 334;
  ext = 335;
  extendedGraphemeClusterLiteral = 336;
  ExtendedGraphemeClusterLiteralType = 337;
  extendedMessage = 338;
  ExtendedMessageResolver = 339;
  extendee = 340;
  extensibilityMode = 341;
  extensible = 342;
  extension = 343;
  ExtensionMap = 344;
  extensionRange = 345;
  extensions = 346;
  ExtensionSchema = 347;
  ExtensionStorage = 348;
  ExtensionValueStorage = 349;
  false = 350;
  features = 351;
  FeatureSetEditionDefault = 352;
  featureSupport = 353;
  field = 354;
  fieldCount = 355;
  fieldHasPresence = 356;
  fieldMask = 357;
  FieldMaskError = 358;
  fieldMaskPaths = 359;
  fieldMode = 360;
  fieldName = 361;
  fieldNameCount = 362;
  fieldNumber = 363;
  FieldOrExtensionSchema = 364;
  fieldPresence = 365;
  fields = 366;
  fieldSchemaSize = 367;
  fieldSize = 368;
  FieldTag = 369;
  file = 370;
  fileName = 371;
  final = 372;
  firstItem = 373;
  firstNontrivialOffset = 374;
  fixed2ByteBase128 = 375;
  fixed32 = 376;
  fixed3ByteBase128 = 377;
  fixed64 = 378;
  fixedFeatures = 379;
  Float = 380;
  floatLiteral = 381;
  FloatLiteralType = 382;
  floatValue = 383;
  floatValueValue = 384;
  for = 385;
  forAssumedPresentRepeatedEnumField = 386;
  forAssumedPresentRepeatedMessageField = 387;
  forAssumedPresentSingularMessageField = 388;
  forCumulativeFrequency = 389;
  forEachMapEntry = 390;
  forEachMessage = 391;
  forEachRawValue = 392;
  forEnumCase = 393;
  forFieldNumber = 394;
  ForGeneratedCodeOnly = 395;
  forJSONName = 396;
  forLazyMapEntry = 397;
  forMapEntry = 398;
  formatDuration = 399;
  formatTimestamp = 400;
  forMessageName = 401;
  formUnion = 402;
  forNewlyAppendedElementOfRepeatedMessageField = 403;
  forSingularMessageField = 404;
  forTextName = 405;
  forTypeURL = 406;
  ForwardParser = 407;
  forWritingInto = 408;
  fractionalDigits = 409;
  frequencies = 410;
  frequency = 411;
  FrequencyModel = 412;
  frequencyRange = 413;
  from = 414;
  fromAscii2 = 415;
  fromAscii4 = 416;
  fromByteOffset = 417;
  fullName = 418;
  func = 419;
  function = 420;
  GeneratedMessage = 421;
  get = 422;
  Google_Protobuf_Any = 423;
  Google_Protobuf_Api = 424;
  Google_Protobuf_BoolValue = 425;
  Google_Protobuf_BytesValue = 426;
  Google_Protobuf_DescriptorProto = 427;
  Google_Protobuf_DoubleValue = 428;
  Google_Protobuf_Duration = 429;
  Google_Protobuf_Edition = 430;
  Google_Protobuf_Empty = 431;
  Google_Protobuf_Enum = 432;
  Google_Protobuf_EnumDescriptorProto = 433;
  Google_Protobuf_EnumOptions = 434;
  Google_Protobuf_EnumValue = 435;
  Google_Protobuf_EnumValueDescriptorProto = 436;
  Google_Protobuf_EnumValueOptions = 437;
  Google_Protobuf_ExtensionRangeOptions = 438;
  Google_Protobuf_FeatureSet = 439;
  Google_Protobuf_FeatureSetDefaults = 440;
  Google_Protobuf_Field = 441;
  Google_Protobuf_FieldDescriptorProto = 442;
  Google_Protobuf_FieldMask = 443;
  Google_Protobuf_FieldOptions = 444;
  Google_Protobuf_FileDescriptorProto = 445;
  Google_Protobuf_FileDescriptorSet = 446;
  Google_Protobuf_FileOptions = 447;
  Google_Protobuf_FloatValue = 448;
  Google_Protobuf_GeneratedCodeInfo = 449;
  Google_Protobuf_Int32Value = 450;
  Google_Protobuf_Int64Value = 451;
  Google_Protobuf_ListValue = 452;
  Google_Protobuf_MessageOptions = 453;
  Google_Protobuf_Method = 454;
  Google_Protobuf_MethodDescriptorProto = 455;
  Google_Protobuf_MethodOptions = 456;
  Google_Protobuf_Mixin = 457;
  Google_Protobuf_NullValue = 458;
  Google_Protobuf_OneofDescriptorProto = 459;
  Google_Protobuf_OneofOptions = 460;
  Google_Protobuf_Option = 461;
  Google_Protobuf_ServiceDescriptorProto = 462;
  Google_Protobuf_ServiceOptions = 463;
  Google_Protobuf_SourceCodeInfo = 464;
  Google_Protobuf_SourceContext = 465;
  Google_Protobuf_StringValue = 466;
  Google_Protobuf_Struct = 467;
  Google_Protobuf_SymbolVisibility = 468;
  Google_Protobuf_Syntax = 469;
  Google_Protobuf_Timestamp = 470;
  Google_Protobuf_Type = 471;
  Google_Protobuf_UInt32Value = 472;
  Google_Protobuf_UInt64Value = 473;
  Google_Protobuf_UninterpretedOption = 474;
  Google_Protobuf_Value = 475;
  goPackage = 476;
  gotNextElement = 477;
  group = 478;
  groupFieldNumberStack = 479;
  hadFieldsOtherThanValue = 480;
  hasAggregateValue = 481;
  hasAllowAlias = 482;
  hasAvailableData = 483;
  hasBegin = 484;
  HasBit = 485;
  hasCcEnableArenas = 486;
  hasCcGenericServices = 487;
  hasClientStreaming = 488;
  hasCsharpNamespace = 489;
  hasCtype = 490;
  hasDebugRedact = 491;
  hasDefaultSymbolVisibility = 492;
  hasDefaultValue = 493;
  hasDeprecated = 494;
  hasDeprecatedLegacyJsonFieldConflicts = 495;
  hasDeprecationWarning = 496;
  hasDoubleValue = 497;
  hasEdition = 498;
  hasEditionDeprecated = 499;
  hasEditionIntroduced = 500;
  hasEditionRemoved = 501;
  hasEnd = 502;
  hasEnforceNamingStyle = 503;
  hasEnforceProtoLimits = 504;
  hasEnumType = 505;
  hasEscapes = 506;
  hasExtendee = 507;
  hasFeatures = 508;
  hasFeatureSupport = 509;
  hasFieldPresence = 510;
  hasFixedFeatures = 511;
  hasFullName = 512;
  hasGoPackage = 513;
  hash = 514;
  Hashable = 515;
  hasher = 516;
  hasIdempotencyLevel = 517;
  hasIdentifierValue = 518;
  hasInputType = 519;
  hasIsExtension = 520;
  hasJavaGenerateEqualsAndHash = 521;
  hasJavaGenericServices = 522;
  hasJavaMultipleFiles = 523;
  hasJavaOuterClassname = 524;
  hasJavaPackage = 525;
  hasJavaStringCheckUtf8 = 526;
  hasJsonFormat = 527;
  hasJsonName = 528;
  hasJstype = 529;
  hasLabel = 530;
  hasLazy = 531;
  hasLeadingComments = 532;
  hasMapEntry = 533;
  hasMaximumEdition = 534;
  hasMessageEncoding = 535;
  hasMessageSetWireFormat = 536;
  hasMinimumEdition = 537;
  hasName = 538;
  hasNamePart = 539;
  hasNegativeIntValue = 540;
  hasNonEmptyNullRepresentation = 541;
  hasNoStandardDescriptorAccessor = 542;
  hasNumber = 543;
  hasObjcClassPrefix = 544;
  hasOneofIndex = 545;
  hasOptimizeFor = 546;
  hasOptions = 547;
  hasOutputType = 548;
  hasOverridableFeatures = 549;
  hasPackage = 550;
  hasPacked = 551;
  hasPhpClassPrefix = 552;
  hasPhpMetadataNamespace = 553;
  hasPhpNamespace = 554;
  hasPositiveIntValue = 555;
  hasProto3Optional = 556;
  hasPyGenericServices = 557;
  hasRemovalError = 558;
  hasRepeated = 559;
  hasRepeatedFieldEncoding = 560;
  hasReserved = 561;
  hasRetention = 562;
  hasRubyPackage = 563;
  hasSemantic = 564;
  hasServerStreaming = 565;
  hasSourceCodeInfo = 566;
  hasSourceContext = 567;
  hasSourceFile = 568;
  hasStart = 569;
  hasStringValue = 570;
  hasSwiftPrefix = 571;
  hasSyntax = 572;
  hasTrailingComments = 573;
  hasType = 574;
  hasTypeName = 575;
  hasUnverifiedLazy = 576;
  hasUtf8Validation = 577;
  hasValue = 578;
  hasVerification = 579;
  hasVisibility = 580;
  hasWeak = 581;
  high = 582;
  highSurrogate = 583;
  hour = 584;
  i = 585;
  idempotencyLevel = 586;
  identifierValue = 587;
  idx = 588;
  if = 589;
  ignored = 590;
  ignoreUnknownExtensionFields = 591;
  ignoreUnknownFields = 592;
  in = 593;
  inAssumedPresentRepeatedEnumField = 594;
  incrementFrequency = 595;
  incrementRecursionBudget = 596;
  index = 597;
  init = 598;
  inout = 599;
  input = 600;
  inputType = 601;
  insert = 602;
  insertMapEntry = 603;
  Int = 604;
  Int32 = 605;
  int32ValueValue = 606;
  Int64 = 607;
  int64ValueValue = 608;
  integerLiteral = 609;
  IntegerLiteralType = 610;
  integerValue = 611;
  intersect = 612;
  into = 613;
  ints = 614;
  invalidAnyTypeURL = 615;
  invalidValues = 616;
  invokeWitness = 617;
  InvokeWitnessFunction = 618;
  isA = 619;
  isAlphanumeric = 620;
  isDigit = 621;
  isEqual = 622;
  isEqualTo = 623;
  isEscape = 624;
  isExtension = 625;
  isField = 626;
  isFieldNameReserved = 627;
  isFieldNumberReserved = 628;
  isFloat = 629;
  isHexDigit = 630;
  isHexNumber = 631;
  isIdentifier = 632;
  isInitialized = 633;
  isJSONEscape = 634;
  isJSONSymbol = 635;
  isLetter = 636;
  isMapField = 637;
  isMessageInitializedRecursive = 638;
  isMessageInitializedShallow = 639;
  isNameReserved = 640;
  isNegative = 641;
  isNumberReserved = 642;
  isOctalDigit = 643;
  isOctalNumber = 644;
  isPacked = 645;
  isPathValid = 646;
  isPresent = 647;
  isPrintableASCII = 648;
  isShallowInitCheckPassed = 649;
  isTrackingGroup = 650;
  isTypeURLValid = 651;
  isUnprintable = 652;
  isURLCharacter = 653;
  isValid = 654;
  isValidValue = 655;
  isWhitespace = 656;
  iterator = 657;
  iteratorAlignment = 658;
  iteratorSize = 659;
  javaGenerateEqualsAndHash = 660;
  javaGenericServices = 661;
  javaMultipleFiles = 662;
  javaOuterClassname = 663;
  javaPackage = 664;
  javaStringCheckUtf8 = 665;
  json = 666;
  JSONDecoding = 667;
  JSONDecodingError = 668;
  JSONDecodingOptions = 669;
  JSONEncoder = 670;
  JSONEncoding = 671;
  JSONEncodingError = 672;
  JSONEncodingOptions = 673;
  jsonFormat = 674;
  jsonName = 675;
  jsonPath = 676;
  jsonPaths = 677;
  JSONReader = 678;
  jsonString = 679;
  jsonUTF8Bytes = 680;
  jsonUTF8Data = 681;
  jstype = 682;
  K = 683;
  kChunkSize = 684;
  keeping = 685;
  Key = 686;
  keyLessThan = 687;
  kind = 688;
  kinds = 689;
  label = 690;
  lastConsumed = 691;
  lazy = 692;
  leadingComments = 693;
  leadingDetachedComments = 694;
  leadingZeroBitCount = 695;
  length = 696;
  lengthBits = 697;
  lengthModel = 698;
  let = 699;
  lexicographicallyPrecedes = 700;
  lhs = 701;
  lhsIter = 702;
  line = 703;
  listValue = 704;
  listValueValues = 705;
  littleEndian = 706;
  load = 707;
  location = 708;
  lock = 709;
  LockPrimitive = 710;
  low = 711;
  M = 712;
  mainModel = 713;
  mainModelSize = 714;
  major = 715;
  makeAsyncIterator = 716;
  makeError = 717;
  makeIterator = 718;
  malformedLength = 719;
  map = 720;
  mapEntry = 721;
  mapEntryKey = 722;
  mapEntryValue = 723;
  MapEntryWitnesses = 724;
  mapEntryWorkingSpace = 725;
  mapValue = 726;
  mask = 727;
  matchCode = 728;
  maximumEdition = 729;
  maxMatchLength = 730;
  mdayStart = 731;
  merge = 732;
  MergeOptions = 733;
  Message = 734;
  messageBytes = 735;
  messageDepthLimit = 736;
  messageEncoding = 737;
  messageName = 738;
  MessageSchema = 739;
  messageSet = 740;
  messageSetItem = 741;
  messageSetItemTagsEncodedSize = 742;
  messageSetMessage = 743;
  messageSetTypeID = 744;
  messageSetWireFormat = 745;
  messageSize = 746;
  messageStorage = 747;
  MessageStorageToken = 748;
  messageType = 749;
  messageValue = 750;
  MessageWitnesses = 751;
  MessageWitnessOperation = 752;
  method = 753;
  methods = 754;
  min = 755;
  minimumEdition = 756;
  minMatchLength = 757;
  minor = 758;
  mixins = 759;
  mode = 760;
  month = 761;
  mutating = 762;
  mutex = 763;
  n = 764;
  name = 765;
  named = 766;
  NamePart = 767;
  nanos = 768;
  negative = 769;
  negativeIntValue = 770;
  nestedType = 771;
  newTotal = 772;
  newValue = 773;
  next = 774;
  nextByte = 775;
  nextLengthDelimitedSlice = 776;
  nextLittleEndianUInt32 = 777;
  nextLittleEndianUInt64 = 778;
  nextTag = 779;
  nextVarInt = 780;
  nextVarintAsValidatedDelimitedLength = 781;
  nil = 782;
  nilLiteral = 783;
  noBytesAvailable = 784;
  nonextensible = 785;
  nonisolated = 786;
  noStandardDescriptorAccessor = 787;
  nullValue = 788;
  number = 789;
  numberValue = 790;
  objcClassPrefix = 791;
  of = 792;
  ofBytesFieldAtIndex = 793;
  offset = 794;
  offsetModel = 795;
  offsetOrIndexValue = 796;
  ofMapFieldAtIndex = 797;
  ofMessageFieldAtIndex = 798;
  ofRepeatedFieldAtIndex = 799;
  ofStringFieldAtIndex = 800;
  ofTagWithFieldNumber = 801;
  oneofDecl = 802;
  oneofIndex = 803;
  oneofOffset = 804;
  OneofPresence = 805;
  oneofs = 806;
  OneOf_Kind = 807;
  operation = 808;
  optimizeFor = 809;
  OptimizeMode = 810;
  Optional = 811;
  optionDependency = 812;
  OptionRetention = 813;
  options = 814;
  OptionTargetType = 815;
  other = 816;
  output = 817;
  outputBytes = 818;
  outputType = 819;
  overridableFeatures = 820;
  ownerSchema = 821;
  p = 822;
  package = 823;
  packed = 824;
  packedBucketOffsetsHi = 825;
  packedBucketOffsetsLo = 826;
  packedBucketStrides = 827;
  padding = 828;
  parse = 829;
  parseDuration = 830;
  parseJSONBuffer = 831;
  parseTimestamp = 832;
  parsingError = 833;
  partial = 834;
  path = 835;
  paths = 836;
  perform = 837;
  phpClassPrefix = 838;
  phpMetadataNamespace = 839;
  phpNamespace = 840;
  pointer = 841;
  populatedOneofMember = 842;
  pos = 843;
  positiveIntValue = 844;
  possibleWKTValueJSON = 845;
  prefix = 846;
  presence = 847;
  preserveProtoFieldNames = 848;
  printUnknownFields = 849;
  proto3Optional = 850;
  ProtobufAPIVersionCheck = 851;
  ProtobufAPIVersion_2 = 852;
  protobufBytes = 853;
  protobufData = 854;
  ProtobufMapBoolField = 855;
  ProtobufMapDataField = 856;
  ProtobufMapDoubleField = 857;
  ProtobufMapEnumField = 858;
  ProtobufMapFloatField = 859;
  ProtobufMapInt32Field = 860;
  ProtobufMapInt64Field = 861;
  ProtobufMapKey = 862;
  ProtobufMapKeyKind = 863;
  ProtobufMapMessageField = 864;
  ProtobufMapParticipant = 865;
  ProtobufMapStringField = 866;
  ProtobufMapUInt32Field = 867;
  ProtobufMapUInt64Field = 868;
  protobuf_ensureUniqueStorage = 869;
  protobuf_enumSchemaString = 870;
  protobuf_extensionStorage = 871;
  protobuf_mapWitness = 872;
  protobuf_messageSchemaString = 873;
  protobuf_messageStorage = 874;
  protobuf_reflectionData = 875;
  protobuf_resolveSubmessageOrEnum = 876;
  protobuf_uniqueExtensionStorage = 877;
  protocol = 878;
  ProtoLimitsFeature = 879;
  protoMessageName = 880;
  protoPaths = 881;
  pthread_mutexattr_t = 882;
  public = 883;
  publicDependency = 884;
  putBoolValue = 885;
  putBytesValue = 886;
  putDoubleValue = 887;
  putEnumValue = 888;
  putFixedUInt32 = 889;
  putFixedUInt64 = 890;
  putFloatValue = 891;
  putInt64 = 892;
  putStringValue = 893;
  putUInt64 = 894;
  putUInt64Hex = 895;
  putVarInt = 896;
  putZigZagVarInt = 897;
  pyGenericServices = 898;
  R = 899;
  radix = 900;
  rangeDecoder = 901;
  rawBufferPointer = 902;
  rawChars = 903;
  rawFieldType = 904;
  rawPointer = 905;
  rawPresence = 906;
  RawRepresentable = 907;
  rawValue = 908;
  readBytes = 909;
  reader = 910;
  reason = 911;
  recursionBudget = 912;
  reflection = 913;
  ReflectionTable = 914;
  register = 915;
  release = 916;
  removalError = 917;
  remove = 918;
  repeated = 919;
  repeatedFieldEncoding = 920;
  repeating = 921;
  replaceRepeatedFields = 922;
  reportingURLCharacters = 923;
  requestStreaming = 924;
  requestTypeURL = 925;
  requiredCount = 926;
  requiredSize = 927;
  resolveLazy = 928;
  resolveLazyMapWitness = 929;
  responseStreaming = 930;
  responseTypeURL = 931;
  result = 932;
  retention = 933;
  rethrows = 934;
  revision = 935;
  rhs = 936;
  rhsIter = 937;
  root = 938;
  rubyPackage = 939;
  S = 940;
  sawEndGroup = 941;
  sawSection4Characters = 942;
  sawSection5Characters = 943;
  scalar = 944;
  scalarStride = 945;
  schema = 946;
  seconds = 947;
  seenFields = 948;
  self = 949;
  semantic = 950;
  Sendable = 951;
  Sequence = 952;
  serialize = 953;
  serializeBoolField = 954;
  serializeBytes = 955;
  serializeBytesField = 956;
  serializedBytes = 957;
  serializedBytesSize = 958;
  serializedData = 959;
  serializeDoubleField = 960;
  serializedSize = 961;
  serializeFixed32Field = 962;
  serializeFixed64Field = 963;
  serializeFloatField = 964;
  serializeInt32Field = 965;
  serializeInt64Field = 966;
  serializeJSON = 967;
  serializePackedFixedField = 968;
  serializePackedVarintsField = 969;
  serializeSFixed32Field = 970;
  serializeSFixed64Field = 971;
  serializeSInt32Field = 972;
  serializeSInt64Field = 973;
  serializeStringField = 974;
  serializeText = 975;
  serializeUInt32Field = 976;
  serializeUInt64Field = 977;
  serverStreaming = 978;
  service = 979;
  Set = 980;
  sfixed32 = 981;
  sfixed64 = 982;
  shift = 983;
  sint32 = 984;
  sint64 = 985;
  size = 986;
  skipField = 987;
  skipFieldMessage = 988;
  skipFieldValue = 989;
  slice = 990;
  sliceBySkippingField = 991;
  some = 992;
  source = 993;
  sourceCodeInfo = 994;
  sourceContext = 995;
  sourceEncoding = 996;
  sourceFile = 997;
  SourceLocation = 998;
  span = 999;
  spi = 1000;
  split = 1001;
  stable = 1002;
  start = 1003;
  startArray = 1004;
  startField = 1005;
  startIndex = 1006;
  startMessageField = 1007;
  startRegularField = 1008;
  static = 1009;
  StaticString = 1010;
  storage = 1011;
  storageBucket = 1012;
  String = 1013;
  stringLiteral = 1014;
  StringLiteralType = 1015;
  StringProtocol = 1016;
  stringResult = 1017;
  stringValue = 1018;
  stringValueValue = 1019;
  struct = 1020;
  structFields = 1021;
  structValue = 1022;
  submessageIndex = 1023;
  submessageOrEnumIndex = 1024;
  SubmessageOrEnumResolver = 1025;
  SubmessageOrEnumSchema = 1026;
  SubmessageOrEnumToken = 1027;
  submessageSchema = 1028;
  submessageStorage = 1029;
  subOptions = 1030;
  subPaths = 1031;
  subReader = 1032;
  subscript = 1033;
  subtract = 1034;
  success = 1035;
  sum = 1036;
  Swift = 1037;
  swiftPrefix = 1038;
  SwiftProtobuf = 1039;
  SwiftProtobufContiguousBytes = 1040;
  SwiftProtobufError = 1041;
  symbol = 1042;
  symbolName = 1043;
  syntax = 1044;
  T = 1045;
  tag = 1046;
  tagAndSizeData = 1047;
  tagAndSizeSize = 1048;
  target = 1049;
  targets = 1050;
  testReader = 1051;
  text = 1052;
  textFormat = 1053;
  TextFormatDecoding = 1054;
  textFormatDecodingError = 1055;
  TextFormatDecodingOptions = 1056;
  TextFormatEncoder = 1057;
  TextFormatEncodingOptions = 1058;
  textFormatName = 1059;
  TextFormatReader = 1060;
  textFormatString = 1061;
  textName = 1062;
  thin = 1063;
  throws = 1064;
  timeInterval = 1065;
  timeIntervalSince1970 = 1066;
  timeIntervalSinceReferenceDate = 1067;
  timestampNanos = 1068;
  timestampSeconds = 1069;
  to = 1070;
  Token = 1071;
  tokenizer = 1072;
  tokenType = 1073;
  tooLarge = 1074;
  toRepeatedEnumField = 1075;
  total = 1076;
  totalEntriesSize = 1077;
  totalEnumsSize = 1078;
  totalSize = 1079;
  trailingComments = 1080;
  trim = 1081;
  true = 1082;
  try = 1083;
  tryConsumeComment = 1084;
  tryConsumeWhitespace = 1085;
  type = 1086;
  typealias = 1087;
  typedPointer = 1088;
  TypeEnum = 1089;
  typeName = 1090;
  typePrefix = 1091;
  typeStart = 1092;
  typeURL = 1093;
  UInt16 = 1094;
  UInt32 = 1095;
  uint32ValueValue = 1096;
  UInt64 = 1097;
  uint64ValueValue = 1098;
  UInt8 = 1099;
  unchecked = 1100;
  Unicode = 1101;
  unicodeScalarLiteral = 1102;
  UnicodeScalarLiteralType = 1103;
  uninterpretedOption = 1104;
  union = 1105;
  uniqueMessageStorage = 1106;
  uniqueStorage = 1107;
  unknownAnyTypeURL = 1108;
  unknownFields = 1109;
  UnknownStorage = 1110;
  unlock = 1111;
  Unmanaged = 1112;
  UnsafeBufferPointer = 1113;
  UnsafeMutablePointer = 1114;
  unsafeMutablePointerToValue = 1115;
  UnsafeMutableRawBufferPointer = 1116;
  UnsafeMutableRawPointer = 1117;
  UnsafeRawBufferPointer = 1118;
  UnsafeRawPointer = 1119;
  unverifiedLazy = 1120;
  updateEnumValue = 1121;
  updateMapValue = 1122;
  updateMessageValue = 1123;
  updatePopulatedOneofMember = 1124;
  updatePresence = 1125;
  updateRepeatedEnumValue = 1126;
  updateRepeatedMessageValue = 1127;
  updateValue = 1128;
  upperBound = 1129;
  uppercasedAssumingASCII = 1130;
  url = 1131;
  urlCharacters = 1132;
  urlPrefix = 1133;
  usableFromInline = 1134;
  useDeterministicOrdering = 1135;
  utf8 = 1136;
  utf8CodeUnitsEqual = 1137;
  utf8Error = 1138;
  UTF8Name = 1139;
  utf8Validation = 1140;
  v = 1141;
  value = 1142;
  valueBoolValue = 1143;
  valueCount = 1144;
  valueError = 1145;
  valueListValue = 1146;
  valueNullValue = 1147;
  valueNumberValue = 1148;
  values = 1149;
  valueStringValue = 1150;
  valueStructValue = 1151;
  var = 1152;
  verification = 1153;
  VerificationState = 1154;
  verifyNotNull = 1155;
  Version = 1156;
  versionString = 1157;
  visibility = 1158;
  VisibilityFeature = 1159;
  Void = 1160;
  wasEmpty = 1161;
  wasNameAlreadyConsumed = 1162;
  weak = 1163;
  weakDependency = 1164;
  wereNameAndColonAlreadyConsumed = 1165;
  where = 1166;
  willBeSet = 1167;
  windowSize = 1168;
  windowSizeBits = 1169;
  wireFormat = 1170;
  WireFormatReader = 1171;
  with = 1172;
  withLock = 1173;
  withRawValue = 1174;
  withReaderForNextGroup = 1175;
  withReaderForNextLengthDelimitedSlice = 1176;
  withReaderForNextObject = 1177;
  withTable = 1178;
  withUnsafeBytes = 1179;
  withUnsafeMutableBytes = 1180;
  witness = 1181;
  workingSpace = 1182;
  Wrapped = 1183;
  wrappedValue = 1184;
  written = 1185;
  yday = 1186;
  zeroOut = 1187;
}
