// See Makefile for the logic that generates this
// Protoc errors imply this file is being generated incorrectly
// Swift compile errors are probably bugs in protoc-gen-swift
syntax = "proto3";
package swift_proto_testing.generated;
enum GeneratedSwiftReservedEnum {
  NONE = 0;
  accessToken = 1;
  addPath = 2;
  adjusted = 3;
  advance = 4;
  aggregateValue = 5;
  allCases = 6;
  allowAlias = 7;
  allowPartial = 8;
  allowSurrogates = 9;
  allowURLCharacters = 10;
  allSubmessagesAreInitialized = 11;
  alwaysPrintEnumsAsInts = 12;
  alwaysPrintInt64sAsNumbers = 13;
  annotation = 14;
  any = 15;
  AnyObject = 16;
  anyOf = 17;
  anyTypeURL = 18;
  AnyUnpackError = 19;
  anyValue = 20;
  append = 21;
  appendEnumValue = 22;
  appendInterpolation = 23;
  appendUIntHex = 24;
  appendUnknown = 25;
  appendValue = 26;
  areAllInitialized = 27;
  Array = 28;
  arrayLiteral = 29;
  arraySeparator = 30;
  as = 31;
  asciiValue = 32;
  asQuotedString = 33;
  assumedPresentValue = 34;
  async = 35;
  AsyncIterator = 36;
  AsyncIteratorProtocol = 37;
  AsyncMessageSequence = 38;
  at = 39;
  atByteOffset = 40;
  atIndex = 41;
  available = 42;
  Base = 43;
  baseAddress = 44;
  begin = 45;
  BinaryDecoding = 46;
  BinaryDecodingError = 47;
  BinaryDecodingOptions = 48;
  BinaryDelimited = 49;
  BinaryEncoder = 50;
  BinaryEncodingError = 51;
  BinaryEncodingOptions = 52;
  binaryProtobufDelimitedMessages = 53;
  BinaryStreamDecoding = 54;
  binaryStreamDecodingError = 55;
  Bit7Reader = 56;
  bitCount = 57;
  bitMask = 58;
  bitPattern = 59;
  BitwiseCopyable = 60;
  body = 61;
  Bool = 62;
  booleanLiteral = 63;
  BooleanLiteralType = 64;
  boolValue = 65;
  boolValueValue = 66;
  borrowing = 67;
  buffer = 68;
  byParsingJSONFrom = 69;
  byParsingTextFormatFrom = 70;
  byte = 71;
  byteOffset = 72;
  bytes = 73;
  bytesInGroup = 74;
  bytesNeeded = 75;
  bytesRead = 76;
  bytesValue = 77;
  bytesValueValue = 78;
  C = 79;
  callAsFunction = 80;
  canonical = 81;
  cardinality = 82;
  CaseIterable = 83;
  ccEnableArenas = 84;
  ccGenericServices = 85;
  CChar = 86;
  changed = 87;
  Character = 88;
  chars = 89;
  chunk = 90;
  class = 91;
  clearAggregateValue = 92;
  clearAllowAlias = 93;
  clearBegin = 94;
  clearCcEnableArenas = 95;
  clearCcGenericServices = 96;
  clearClientStreaming = 97;
  clearCsharpNamespace = 98;
  clearCtype = 99;
  clearDebugRedact = 100;
  clearDefaultSymbolVisibility = 101;
  clearDefaultValue = 102;
  clearDeprecated = 103;
  clearDeprecatedLegacyJsonFieldConflicts = 104;
  clearDeprecationWarning = 105;
  clearDoubleValue = 106;
  clearEdition = 107;
  clearEditionDeprecated = 108;
  clearEditionIntroduced = 109;
  clearEditionRemoved = 110;
  clearEnd = 111;
  clearEnforceNamingStyle = 112;
  clearEnforceProtoLimits = 113;
  clearEnumType = 114;
  clearExtendee = 115;
  clearFeatures = 116;
  clearFeatureSupport = 117;
  clearFieldPresence = 118;
  clearFixedFeatures = 119;
  clearFullName = 120;
  clearGoPackage = 121;
  clearIdempotencyLevel = 122;
  clearIdentifierValue = 123;
  clearInputType = 124;
  clearIsExtension = 125;
  clearJavaGenerateEqualsAndHash = 126;
  clearJavaGenericServices = 127;
  clearJavaMultipleFiles = 128;
  clearJavaOuterClassname = 129;
  clearJavaPackage = 130;
  clearJavaStringCheckUtf8 = 131;
  clearJsonFormat = 132;
  clearJsonName = 133;
  clearJstype = 134;
  clearLabel = 135;
  clearLazy = 136;
  clearLeadingComments = 137;
  clearMapEntry = 138;
  clearMaximumEdition = 139;
  clearMessageEncoding = 140;
  clearMessageSetWireFormat = 141;
  clearMinimumEdition = 142;
  clearName = 143;
  clearNamePart = 144;
  clearNegativeIntValue = 145;
  clearNoStandardDescriptorAccessor = 146;
  clearNumber = 147;
  clearObjcClassPrefix = 148;
  clearOneofIndex = 149;
  clearOptimizeFor = 150;
  clearOptions = 151;
  clearOutputType = 152;
  clearOverridableFeatures = 153;
  clearPackage = 154;
  clearPacked = 155;
  clearPhpClassPrefix = 156;
  clearPhpMetadataNamespace = 157;
  clearPhpNamespace = 158;
  clearPopulatedOneofMember = 159;
  clearPositiveIntValue = 160;
  clearProto3Optional = 161;
  clearPyGenericServices = 162;
  clearRemovalError = 163;
  clearRepeated = 164;
  clearRepeatedFieldEncoding = 165;
  clearRepeatedOrMapField = 166;
  clearReserved = 167;
  clearRetention = 168;
  clearRubyPackage = 169;
  clearSemantic = 170;
  clearServerStreaming = 171;
  clearSingularMessageField = 172;
  clearSourceCodeInfo = 173;
  clearSourceContext = 174;
  clearSourceFile = 175;
  clearStart = 176;
  clearStringValue = 177;
  clearSwiftPrefix = 178;
  clearSyntax = 179;
  clearTrailingComments = 180;
  clearType = 181;
  clearTypeName = 182;
  clearUnverifiedLazy = 183;
  clearUtf8Validation = 184;
  clearValue = 185;
  clearVerification = 186;
  clearVisibility = 187;
  clearWeak = 188;
  clientStreaming = 189;
  Code = 190;
  codeUnits = 191;
  Collection = 192;
  complete = 193;
  compressed = 194;
  computedSize = 195;
  consume = 196;
  consumeAnyTypeURLOrExtensionName = 197;
  consumeArray = 198;
  consumeBool = 199;
  consumeBytes = 200;
  consumedBytes = 201;
  consumeDouble = 202;
  consumeEnumValue = 203;
  consumeFieldOrExtension = 204;
  consumeFieldOrExtensionIfPresent = 205;
  consumeFieldSeparatorIfPresent = 206;
  consumeFloat = 207;
  consumeIdentifier = 208;
  consumeIfPresent = 209;
  consumeLineComment = 210;
  consumeNullIfPresent = 211;
  consumeObject = 212;
  consumePossibleArray = 213;
  consumePrefix = 214;
  consumeSignedInteger = 215;
  consumeString = 216;
  consumeUnsignedDecimalAsDouble = 217;
  consumeUnsignedInteger = 218;
  contains = 219;
  contentsOf = 220;
  ContiguousBytes = 221;
  copy = 222;
  count = 223;
  countVarintsInBuffer = 224;
  csharpNamespace = 225;
  ctype = 226;
  cumulative = 227;
  cumulativeFrequency = 228;
  current = 229;
  currentOffset = 230;
  currentSchema = 231;
  currentSum = 232;
  CustomDebugStringConvertible = 233;
  CustomStringConvertible = 234;
  data = 235;
  date = 236;
  daySec = 237;
  daysSinceEpoch = 238;
  debugDescription = 239;
  debugRedact = 240;
  declaration = 241;
  decode = 242;
  decodeNextExtension = 243;
  decodingOptions = 244;
  decompress = 245;
  decrementRecursionBudget = 246;
  default = 247;
  defaultAnyTypeURLPrefix = 248;
  defaults = 249;
  defaultSymbolVisibility = 250;
  defaultValue = 251;
  deinitializeField = 252;
  deinitializeFieldForced = 253;
  delimiter = 254;
  denseBelow = 255;
  dependency = 256;
  deprecated = 257;
  deprecatedLegacyJsonFieldConflicts = 258;
  deprecationWarning = 259;
  description = 260;
  dictionaryLiteral = 261;
  digit0 = 262;
  digit1 = 263;
  digitCount = 264;
  digits = 265;
  digitValue = 266;
  discardableResult = 267;
  discardUnknownFields = 268;
  Double = 269;
  doubleValue = 270;
  doubleValueValue = 271;
  duration = 272;
  durationNanos = 273;
  durationSeconds = 274;
  E = 275;
  edition = 276;
  EditionDefault = 277;
  editionDefaults = 278;
  editionDeprecated = 279;
  editionIntroduced = 280;
  editionRemoved = 281;
  Element = 282;
  elementCount = 283;
  elements = 284;
  elementsBuffer = 285;
  elementsReader = 286;
  emitExtensionFieldName = 287;
  emitFieldName = 288;
  emitFieldNumber = 289;
  emitRepeatedField = 290;
  emitValue = 291;
  emptyAnyTypeURL = 292;
  encodeAsBytes = 293;
  encodedSize = 294;
  encoder = 295;
  end = 296;
  endArray = 297;
  endMessageField = 298;
  endRegularField = 299;
  enforceNamingStyle = 300;
  enforceProtoLimits = 301;
  enum = 302;
  enumCase = 303;
  enumName = 304;
  EnumReservedRange = 305;
  enumSchema = 306;
  enumType = 307;
  enumvalue = 308;
  EnumWitnesses = 309;
  EnumWitnessOperation = 310;
  equalSoFar = 311;
  equalToSameFieldIn = 312;
  Equatable = 313;
  Error = 314;
  errorCode = 315;
  errorDescription = 316;
  escapeCode = 317;
  escapeModel = 318;
  escaping = 319;
  exactString = 320;
  expected = 321;
  explicitPresenceCount = 322;
  ExpressibleByArrayLiteral = 323;
  ext = 324;
  extendedGraphemeClusterLiteral = 325;
  ExtendedGraphemeClusterLiteralType = 326;
  extendedMessage = 327;
  ExtendedMessageResolver = 328;
  extendee = 329;
  extensibilityMode = 330;
  extensible = 331;
  extension = 332;
  ExtensionMap = 333;
  extensionRange = 334;
  extensions = 335;
  ExtensionSchema = 336;
  ExtensionStorage = 337;
  ExtensionValueStorage = 338;
  false = 339;
  features = 340;
  FeatureSetEditionDefault = 341;
  featureSupport = 342;
  field = 343;
  fieldCount = 344;
  fieldHasPresence = 345;
  fieldMask = 346;
  FieldMaskError = 347;
  fieldMaskPaths = 348;
  fieldMode = 349;
  fieldName = 350;
  fieldNameCount = 351;
  fieldNumber = 352;
  FieldOrExtensionSchema = 353;
  fieldPresence = 354;
  fields = 355;
  fieldSchemaSize = 356;
  fieldSize = 357;
  FieldTag = 358;
  file = 359;
  fileName = 360;
  final = 361;
  firstItem = 362;
  firstNontrivialOffset = 363;
  fixed2ByteBase128 = 364;
  fixed32 = 365;
  fixed3ByteBase128 = 366;
  fixed64 = 367;
  fixedFeatures = 368;
  Float = 369;
  floatLiteral = 370;
  FloatLiteralType = 371;
  floatValue = 372;
  floatValueValue = 373;
  for = 374;
  forAssumedPresentRepeatedEnumField = 375;
  forAssumedPresentRepeatedMessageField = 376;
  forAssumedPresentSingularMessageField = 377;
  forCumulativeFrequency = 378;
  forEachMapEntry = 379;
  forEachMessage = 380;
  forEachRawValue = 381;
  forEnumCase = 382;
  forFieldNumber = 383;
  ForGeneratedCodeOnly = 384;
  forJSONName = 385;
  formatDuration = 386;
  formatTimestamp = 387;
  forMessageName = 388;
  formUnion = 389;
  forNewlyAppendedElementOfRepeatedMessageField = 390;
  forSingularMessageField = 391;
  forTextName = 392;
  forTypeURL = 393;
  ForwardParser = 394;
  forWritingInto = 395;
  fractionalDigits = 396;
  frequencies = 397;
  frequency = 398;
  FrequencyModel = 399;
  frequencyRange = 400;
  from = 401;
  fromAscii2 = 402;
  fromAscii4 = 403;
  fromByteOffset = 404;
  fullName = 405;
  func = 406;
  function = 407;
  GeneratedMessage = 408;
  get = 409;
  Google_Protobuf_Any = 410;
  Google_Protobuf_Api = 411;
  Google_Protobuf_BoolValue = 412;
  Google_Protobuf_BytesValue = 413;
  Google_Protobuf_DescriptorProto = 414;
  Google_Protobuf_DoubleValue = 415;
  Google_Protobuf_Duration = 416;
  Google_Protobuf_Edition = 417;
  Google_Protobuf_Empty = 418;
  Google_Protobuf_Enum = 419;
  Google_Protobuf_EnumDescriptorProto = 420;
  Google_Protobuf_EnumOptions = 421;
  Google_Protobuf_EnumValue = 422;
  Google_Protobuf_EnumValueDescriptorProto = 423;
  Google_Protobuf_EnumValueOptions = 424;
  Google_Protobuf_ExtensionRangeOptions = 425;
  Google_Protobuf_FeatureSet = 426;
  Google_Protobuf_FeatureSetDefaults = 427;
  Google_Protobuf_Field = 428;
  Google_Protobuf_FieldDescriptorProto = 429;
  Google_Protobuf_FieldMask = 430;
  Google_Protobuf_FieldOptions = 431;
  Google_Protobuf_FileDescriptorProto = 432;
  Google_Protobuf_FileDescriptorSet = 433;
  Google_Protobuf_FileOptions = 434;
  Google_Protobuf_FloatValue = 435;
  Google_Protobuf_GeneratedCodeInfo = 436;
  Google_Protobuf_Int32Value = 437;
  Google_Protobuf_Int64Value = 438;
  Google_Protobuf_ListValue = 439;
  Google_Protobuf_MessageOptions = 440;
  Google_Protobuf_Method = 441;
  Google_Protobuf_MethodDescriptorProto = 442;
  Google_Protobuf_MethodOptions = 443;
  Google_Protobuf_Mixin = 444;
  Google_Protobuf_NullValue = 445;
  Google_Protobuf_OneofDescriptorProto = 446;
  Google_Protobuf_OneofOptions = 447;
  Google_Protobuf_Option = 448;
  Google_Protobuf_ServiceDescriptorProto = 449;
  Google_Protobuf_ServiceOptions = 450;
  Google_Protobuf_SourceCodeInfo = 451;
  Google_Protobuf_SourceContext = 452;
  Google_Protobuf_StringValue = 453;
  Google_Protobuf_Struct = 454;
  Google_Protobuf_SymbolVisibility = 455;
  Google_Protobuf_Syntax = 456;
  Google_Protobuf_Timestamp = 457;
  Google_Protobuf_Type = 458;
  Google_Protobuf_UInt32Value = 459;
  Google_Protobuf_UInt64Value = 460;
  Google_Protobuf_UninterpretedOption = 461;
  Google_Protobuf_Value = 462;
  goPackage = 463;
  gotNextElement = 464;
  group = 465;
  groupFieldNumberStack = 466;
  hadFieldsOtherThanValue = 467;
  hasAggregateValue = 468;
  hasAllowAlias = 469;
  hasAvailableData = 470;
  hasBegin = 471;
  HasBit = 472;
  hasCcEnableArenas = 473;
  hasCcGenericServices = 474;
  hasClientStreaming = 475;
  hasCsharpNamespace = 476;
  hasCtype = 477;
  hasDebugRedact = 478;
  hasDefaultSymbolVisibility = 479;
  hasDefaultValue = 480;
  hasDeprecated = 481;
  hasDeprecatedLegacyJsonFieldConflicts = 482;
  hasDeprecationWarning = 483;
  hasDoubleValue = 484;
  hasEdition = 485;
  hasEditionDeprecated = 486;
  hasEditionIntroduced = 487;
  hasEditionRemoved = 488;
  hasEnd = 489;
  hasEnforceNamingStyle = 490;
  hasEnforceProtoLimits = 491;
  hasEnumType = 492;
  hasEscapes = 493;
  hasExtendee = 494;
  hasFeatures = 495;
  hasFeatureSupport = 496;
  hasFieldPresence = 497;
  hasFixedFeatures = 498;
  hasFullName = 499;
  hasGoPackage = 500;
  hash = 501;
  Hashable = 502;
  hasher = 503;
  hasIdempotencyLevel = 504;
  hasIdentifierValue = 505;
  hasInputType = 506;
  hasIsExtension = 507;
  hasJavaGenerateEqualsAndHash = 508;
  hasJavaGenericServices = 509;
  hasJavaMultipleFiles = 510;
  hasJavaOuterClassname = 511;
  hasJavaPackage = 512;
  hasJavaStringCheckUtf8 = 513;
  hasJsonFormat = 514;
  hasJsonName = 515;
  hasJstype = 516;
  hasLabel = 517;
  hasLazy = 518;
  hasLeadingComments = 519;
  hasMapEntry = 520;
  hasMaximumEdition = 521;
  hasMessageEncoding = 522;
  hasMessageSetWireFormat = 523;
  hasMinimumEdition = 524;
  hasName = 525;
  hasNamePart = 526;
  hasNegativeIntValue = 527;
  hasNonEmptyNullRepresentation = 528;
  hasNoStandardDescriptorAccessor = 529;
  hasNumber = 530;
  hasObjcClassPrefix = 531;
  hasOneofIndex = 532;
  hasOptimizeFor = 533;
  hasOptions = 534;
  hasOutputType = 535;
  hasOverridableFeatures = 536;
  hasPackage = 537;
  hasPacked = 538;
  hasPhpClassPrefix = 539;
  hasPhpMetadataNamespace = 540;
  hasPhpNamespace = 541;
  hasPositiveIntValue = 542;
  hasProto3Optional = 543;
  hasPyGenericServices = 544;
  hasRemovalError = 545;
  hasRepeated = 546;
  hasRepeatedFieldEncoding = 547;
  hasReserved = 548;
  hasRetention = 549;
  hasRubyPackage = 550;
  hasSemantic = 551;
  hasServerStreaming = 552;
  hasSourceCodeInfo = 553;
  hasSourceContext = 554;
  hasSourceFile = 555;
  hasStart = 556;
  hasStringValue = 557;
  hasSwiftPrefix = 558;
  hasSyntax = 559;
  hasTrailingComments = 560;
  hasType = 561;
  hasTypeName = 562;
  hasUnverifiedLazy = 563;
  hasUtf8Validation = 564;
  hasValue = 565;
  hasVerification = 566;
  hasVisibility = 567;
  hasWeak = 568;
  high = 569;
  highSurrogate = 570;
  hour = 571;
  i = 572;
  idempotencyLevel = 573;
  identifierValue = 574;
  idx = 575;
  if = 576;
  ignored = 577;
  ignoreUnknownExtensionFields = 578;
  ignoreUnknownFields = 579;
  in = 580;
  inAssumedPresentRepeatedEnumField = 581;
  incrementFrequency = 582;
  incrementRecursionBudget = 583;
  index = 584;
  init = 585;
  inout = 586;
  input = 587;
  inputType = 588;
  insert = 589;
  insertMapEntry = 590;
  Int = 591;
  Int32 = 592;
  int32ValueValue = 593;
  Int64 = 594;
  int64ValueValue = 595;
  integerLiteral = 596;
  IntegerLiteralType = 597;
  integerValue = 598;
  intersect = 599;
  into = 600;
  ints = 601;
  invalidAnyTypeURL = 602;
  invalidValues = 603;
  invokeWitness = 604;
  InvokeWitnessFunction = 605;
  isA = 606;
  isAlphanumeric = 607;
  isDigit = 608;
  isEqual = 609;
  isEqualTo = 610;
  isEscape = 611;
  isExtension = 612;
  isField = 613;
  isFieldNameReserved = 614;
  isFieldNumberReserved = 615;
  isFloat = 616;
  isHexDigit = 617;
  isHexNumber = 618;
  isIdentifier = 619;
  isInitialized = 620;
  isJSONEscape = 621;
  isJSONSymbol = 622;
  isLetter = 623;
  isMapField = 624;
  isMessageInitializedRecursive = 625;
  isMessageInitializedShallow = 626;
  isNameReserved = 627;
  isNegative = 628;
  isNumberReserved = 629;
  isOctalDigit = 630;
  isOctalNumber = 631;
  isPacked = 632;
  isPathValid = 633;
  isPresent = 634;
  isPrintableASCII = 635;
  isShallowInitCheckPassed = 636;
  isTrackingGroup = 637;
  isTypeURLValid = 638;
  isUnprintable = 639;
  isURLCharacter = 640;
  isValid = 641;
  isValidValue = 642;
  isWhitespace = 643;
  iterator = 644;
  iteratorAlignment = 645;
  iteratorSize = 646;
  javaGenerateEqualsAndHash = 647;
  javaGenericServices = 648;
  javaMultipleFiles = 649;
  javaOuterClassname = 650;
  javaPackage = 651;
  javaStringCheckUtf8 = 652;
  json = 653;
  JSONDecoding = 654;
  JSONDecodingError = 655;
  JSONDecodingOptions = 656;
  JSONEncoder = 657;
  JSONEncoding = 658;
  JSONEncodingError = 659;
  JSONEncodingOptions = 660;
  jsonFormat = 661;
  jsonName = 662;
  jsonPath = 663;
  jsonPaths = 664;
  JSONReader = 665;
  jsonString = 666;
  jsonUTF8Bytes = 667;
  jsonUTF8Data = 668;
  jstype = 669;
  K = 670;
  kChunkSize = 671;
  keeping = 672;
  Key = 673;
  keyLessThan = 674;
  kind = 675;
  kinds = 676;
  label = 677;
  lastConsumed = 678;
  lazy = 679;
  leadingComments = 680;
  leadingDetachedComments = 681;
  leadingZeroBitCount = 682;
  length = 683;
  lengthBits = 684;
  lengthModel = 685;
  let = 686;
  lexicographicallyPrecedes = 687;
  lhs = 688;
  lhsIter = 689;
  line = 690;
  listValue = 691;
  listValueValues = 692;
  littleEndian = 693;
  load = 694;
  location = 695;
  low = 696;
  M = 697;
  mainModel = 698;
  mainModelSize = 699;
  major = 700;
  makeAsyncIterator = 701;
  makeError = 702;
  makeIterator = 703;
  malformedLength = 704;
  map = 705;
  mapEntry = 706;
  mapEntryKey = 707;
  mapEntryValue = 708;
  MapEntryWitnesses = 709;
  mapEntryWorkingSpace = 710;
  mask = 711;
  matchCode = 712;
  maximumEdition = 713;
  maxMatchLength = 714;
  mdayStart = 715;
  merge = 716;
  MergeOptions = 717;
  Message = 718;
  messageBytes = 719;
  messageDepthLimit = 720;
  messageEncoding = 721;
  messageName = 722;
  MessageSchema = 723;
  messageSet = 724;
  messageSetItem = 725;
  messageSetItemTagsEncodedSize = 726;
  messageSetMessage = 727;
  messageSetTypeID = 728;
  messageSetWireFormat = 729;
  messageSize = 730;
  messageStorage = 731;
  MessageStorageToken = 732;
  messageType = 733;
  MessageWitnesses = 734;
  MessageWitnessOperation = 735;
  method = 736;
  methods = 737;
  min = 738;
  minimumEdition = 739;
  minMatchLength = 740;
  minor = 741;
  mixins = 742;
  mode = 743;
  month = 744;
  mutating = 745;
  n = 746;
  name = 747;
  NamePart = 748;
  nanos = 749;
  negative = 750;
  negativeIntValue = 751;
  nestedType = 752;
  newTotal = 753;
  newValue = 754;
  next = 755;
  nextByte = 756;
  nextLengthDelimitedSlice = 757;
  nextLittleEndianUInt32 = 758;
  nextLittleEndianUInt64 = 759;
  nextTag = 760;
  nextVarInt = 761;
  nextVarintAsValidatedDelimitedLength = 762;
  nil = 763;
  nilLiteral = 764;
  noBytesAvailable = 765;
  nonextensible = 766;
  nonisolated = 767;
  noStandardDescriptorAccessor = 768;
  nullValue = 769;
  number = 770;
  numberValue = 771;
  objcClassPrefix = 772;
  of = 773;
  ofBytesFieldAtIndex = 774;
  offset = 775;
  offsetModel = 776;
  offsetOrIndexValue = 777;
  ofMapFieldAtIndex = 778;
  ofMessageFieldAtIndex = 779;
  ofRepeatedFieldAtIndex = 780;
  ofStringFieldAtIndex = 781;
  ofTagWithFieldNumber = 782;
  oneofDecl = 783;
  oneofIndex = 784;
  oneofOffset = 785;
  OneofPresence = 786;
  oneofs = 787;
  OneOf_Kind = 788;
  operation = 789;
  optimizeFor = 790;
  OptimizeMode = 791;
  Optional = 792;
  optionDependency = 793;
  OptionRetention = 794;
  options = 795;
  OptionTargetType = 796;
  other = 797;
  output = 798;
  outputBytes = 799;
  outputType = 800;
  overridableFeatures = 801;
  ownerSchema = 802;
  p = 803;
  package = 804;
  packed = 805;
  packedBucketOffsetsHi = 806;
  packedBucketOffsetsLo = 807;
  packedBucketStrides = 808;
  padding = 809;
  parse = 810;
  parseDuration = 811;
  parseJSONBuffer = 812;
  parseTimestamp = 813;
  parsingError = 814;
  partial = 815;
  path = 816;
  paths = 817;
  perform = 818;
  phpClassPrefix = 819;
  phpMetadataNamespace = 820;
  phpNamespace = 821;
  pointer = 822;
  populatedOneofMember = 823;
  pos = 824;
  positiveIntValue = 825;
  possibleWKTValueJSON = 826;
  prefix = 827;
  presence = 828;
  preserveProtoFieldNames = 829;
  printUnknownFields = 830;
  proto3Optional = 831;
  ProtobufAPIVersionCheck = 832;
  ProtobufAPIVersion_2 = 833;
  protobufBytes = 834;
  protobufData = 835;
  ProtobufMapBoolField = 836;
  ProtobufMapDataField = 837;
  ProtobufMapDoubleField = 838;
  ProtobufMapEnumField = 839;
  ProtobufMapFloatField = 840;
  ProtobufMapInt32Field = 841;
  ProtobufMapInt64Field = 842;
  ProtobufMapKey = 843;
  ProtobufMapMessageField = 844;
  ProtobufMapParticipant = 845;
  ProtobufMapStringField = 846;
  ProtobufMapUInt32Field = 847;
  ProtobufMapUInt64Field = 848;
  protobuf_ensureUniqueStorage = 849;
  protobuf_enumSchemaString = 850;
  protobuf_extensionStorage = 851;
  protobuf_messageSchemaString = 852;
  protobuf_messageStorage = 853;
  protobuf_reflectionData = 854;
  protobuf_resolveSubmessageOrEnum = 855;
  protobuf_uniqueExtensionStorage = 856;
  protocol = 857;
  ProtoLimitsFeature = 858;
  protoMessageName = 859;
  protoPaths = 860;
  public = 861;
  publicDependency = 862;
  putBoolValue = 863;
  putBytesValue = 864;
  putDoubleValue = 865;
  putEnumValue = 866;
  putFixedUInt32 = 867;
  putFixedUInt64 = 868;
  putFloatValue = 869;
  putInt64 = 870;
  putStringValue = 871;
  putUInt64 = 872;
  putUInt64Hex = 873;
  putVarInt = 874;
  putZigZagVarInt = 875;
  pyGenericServices = 876;
  R = 877;
  radix = 878;
  rangeDecoder = 879;
  rawBufferPointer = 880;
  rawChars = 881;
  rawFieldType = 882;
  rawPointer = 883;
  rawPresence = 884;
  RawRepresentable = 885;
  rawValue = 886;
  readBytes = 887;
  reader = 888;
  reason = 889;
  recursionBudget = 890;
  reflection = 891;
  ReflectionTable = 892;
  register = 893;
  release = 894;
  removalError = 895;
  remove = 896;
  repeated = 897;
  repeatedFieldEncoding = 898;
  repeating = 899;
  replaceRepeatedFields = 900;
  reportingURLCharacters = 901;
  requestStreaming = 902;
  requestTypeURL = 903;
  requiredCount = 904;
  requiredSize = 905;
  responseStreaming = 906;
  responseTypeURL = 907;
  result = 908;
  retention = 909;
  rethrows = 910;
  revision = 911;
  rhs = 912;
  rhsIter = 913;
  root = 914;
  rubyPackage = 915;
  S = 916;
  sawEndGroup = 917;
  sawSection4Characters = 918;
  sawSection5Characters = 919;
  scalar = 920;
  scalarStride = 921;
  schema = 922;
  seconds = 923;
  seenFields = 924;
  self = 925;
  semantic = 926;
  Sendable = 927;
  Sequence = 928;
  serialize = 929;
  serializeBoolField = 930;
  serializeBytes = 931;
  serializeBytesField = 932;
  serializedBytes = 933;
  serializedBytesSize = 934;
  serializedData = 935;
  serializeDoubleField = 936;
  serializedSize = 937;
  serializeFixed32Field = 938;
  serializeFixed64Field = 939;
  serializeFloatField = 940;
  serializeInt32Field = 941;
  serializeInt64Field = 942;
  serializeJSON = 943;
  serializePackedFixedField = 944;
  serializePackedVarintsField = 945;
  serializeSFixed32Field = 946;
  serializeSFixed64Field = 947;
  serializeSInt32Field = 948;
  serializeSInt64Field = 949;
  serializeStringField = 950;
  serializeText = 951;
  serializeUInt32Field = 952;
  serializeUInt64Field = 953;
  serverStreaming = 954;
  service = 955;
  Set = 956;
  sfixed32 = 957;
  sfixed64 = 958;
  shift = 959;
  sint32 = 960;
  sint64 = 961;
  size = 962;
  skipField = 963;
  skipFieldMessage = 964;
  skipFieldValue = 965;
  slice = 966;
  sliceBySkippingField = 967;
  some = 968;
  source = 969;
  sourceCodeInfo = 970;
  sourceContext = 971;
  sourceEncoding = 972;
  sourceFile = 973;
  SourceLocation = 974;
  span = 975;
  spi = 976;
  split = 977;
  stable = 978;
  start = 979;
  startArray = 980;
  startField = 981;
  startIndex = 982;
  startMessageField = 983;
  startRegularField = 984;
  static = 985;
  StaticString = 986;
  storage = 987;
  storageBucket = 988;
  String = 989;
  stringLiteral = 990;
  StringLiteralType = 991;
  StringProtocol = 992;
  stringResult = 993;
  stringValue = 994;
  stringValueValue = 995;
  struct = 996;
  structFields = 997;
  structValue = 998;
  submessageIndex = 999;
  submessageOrEnumIndex = 1000;
  SubmessageOrEnumResolver = 1001;
  SubmessageOrEnumSchema = 1002;
  SubmessageOrEnumToken = 1003;
  submessageStorage = 1004;
  subOptions = 1005;
  subPaths = 1006;
  subReader = 1007;
  subscript = 1008;
  subtract = 1009;
  success = 1010;
  sum = 1011;
  Swift = 1012;
  swiftPrefix = 1013;
  SwiftProtobuf = 1014;
  SwiftProtobufContiguousBytes = 1015;
  SwiftProtobufError = 1016;
  symbol = 1017;
  syntax = 1018;
  T = 1019;
  tag = 1020;
  tagAndSizeData = 1021;
  tagAndSizeSize = 1022;
  target = 1023;
  targets = 1024;
  testReader = 1025;
  text = 1026;
  textFormat = 1027;
  TextFormatDecoding = 1028;
  textFormatDecodingError = 1029;
  TextFormatDecodingOptions = 1030;
  TextFormatEncoder = 1031;
  TextFormatEncodingOptions = 1032;
  textFormatName = 1033;
  TextFormatReader = 1034;
  textFormatString = 1035;
  textName = 1036;
  throws = 1037;
  timeInterval = 1038;
  timeIntervalSince1970 = 1039;
  timeIntervalSinceReferenceDate = 1040;
  timestampNanos = 1041;
  timestampSeconds = 1042;
  to = 1043;
  Token = 1044;
  tokenizer = 1045;
  tokenType = 1046;
  tooLarge = 1047;
  toRepeatedEnumField = 1048;
  total = 1049;
  totalEntriesSize = 1050;
  totalEnumsSize = 1051;
  totalSize = 1052;
  trailingComments = 1053;
  trim = 1054;
  true = 1055;
  try = 1056;
  tryConsumeComment = 1057;
  tryConsumeWhitespace = 1058;
  type = 1059;
  typealias = 1060;
  typedPointer = 1061;
  TypeEnum = 1062;
  typeName = 1063;
  typePrefix = 1064;
  typeStart = 1065;
  typeURL = 1066;
  UInt16 = 1067;
  UInt32 = 1068;
  uint32ValueValue = 1069;
  UInt64 = 1070;
  uint64ValueValue = 1071;
  UInt8 = 1072;
  unchecked = 1073;
  Unicode = 1074;
  unicodeScalarLiteral = 1075;
  UnicodeScalarLiteralType = 1076;
  uninterpretedOption = 1077;
  union = 1078;
  uniqueMessageStorage = 1079;
  uniqueStorage = 1080;
  unknownAnyTypeURL = 1081;
  unknownFields = 1082;
  UnknownStorage = 1083;
  Unmanaged = 1084;
  UnsafeBufferPointer = 1085;
  UnsafeMutablePointer = 1086;
  unsafeMutablePointerToValue = 1087;
  UnsafeMutableRawBufferPointer = 1088;
  unsafeMutableRawPointer = 1089;
  UnsafeRawBufferPointer = 1090;
  unsafeRawPointer = 1091;
  unverifiedLazy = 1092;
  updatePopulatedOneofMember = 1093;
  updatePresence = 1094;
  updateValue = 1095;
  upperBound = 1096;
  uppercasedAssumingASCII = 1097;
  url = 1098;
  urlCharacters = 1099;
  urlPrefix = 1100;
  usableFromInline = 1101;
  useDeterministicOrdering = 1102;
  utf8 = 1103;
  utf8CodeUnitsEqual = 1104;
  utf8Error = 1105;
  UTF8Name = 1106;
  utf8Validation = 1107;
  v = 1108;
  value = 1109;
  valueBoolValue = 1110;
  valueCount = 1111;
  valueError = 1112;
  valueListValue = 1113;
  valueNullValue = 1114;
  valueNumberValue = 1115;
  values = 1116;
  valueStringValue = 1117;
  valueStructValue = 1118;
  var = 1119;
  verification = 1120;
  VerificationState = 1121;
  verifyNotNull = 1122;
  Version = 1123;
  versionString = 1124;
  visibility = 1125;
  VisibilityFeature = 1126;
  Void = 1127;
  wasEmpty = 1128;
  wasNameAlreadyConsumed = 1129;
  weak = 1130;
  weakDependency = 1131;
  wereNameAndColonAlreadyConsumed = 1132;
  where = 1133;
  willBeSet = 1134;
  windowSize = 1135;
  windowSizeBits = 1136;
  wireFormat = 1137;
  WireFormatReader = 1138;
  with = 1139;
  withRawValue = 1140;
  withReaderForNextGroup = 1141;
  withReaderForNextLengthDelimitedSlice = 1142;
  withReaderForNextObject = 1143;
  withTable = 1144;
  withUnsafeBytes = 1145;
  withUnsafeMutableBytes = 1146;
  workingSpace = 1147;
  Wrapped = 1148;
  wrappedValue = 1149;
  written = 1150;
  yday = 1151;
  zeroOut = 1152;
}
